package app

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"graphql-gateway/internal/app/generated"
	"graphql-gateway/internal/clients"
)

// PreviewDocument is the resolver for the previewDocument field.
func (r *mutationResolver) PreviewDocument(ctx context.Context, input generated.PreviewDocumentInput) (*generated.PreviewDocumentResult, error) {
	sourceURL := ""
	if input.SourceURL != nil {
		sourceURL = *input.SourceURL
	}
	contentBase64 := ""
	if input.ContentBase64 != nil {
		contentBase64 = *input.ContentBase64
	}
	urlMaxDepth := int32(0)
	if input.URLMaxDepth != nil {
		urlMaxDepth = int32(*input.URLMaxDepth)
	}

	result, err := r.RAGClient.PreviewDocument(
		ctx,
		input.Title,
		clients.MapDocumentSourceType(string(input.SourceType)),
		sourceURL,
		contentBase64,
		urlMaxDepth,
	)
	if err != nil {
		return nil, err
	}
	return &generated.PreviewDocumentResult{
		ExtractedText:  result.ExtractedText,
		PagesExtracted: int(result.PagesExtracted),
	}, nil
}

// CommitDocument is the resolver for the commitDocument field.
func (r *mutationResolver) CommitDocument(ctx context.Context, input generated.CommitDocumentInput) (*generated.CommitDocumentResult, error) {
	metadata := make([]clients.MetadataEntry, len(input.Metadata))
	for i, m := range input.Metadata {
		metadata[i] = clients.MetadataEntry{Key: m.Key, Value: m.Value}
	}

	content := ""
	if input.Content != nil {
		content = *input.Content
	}
	contentBase64 := ""
	if input.ContentBase64 != nil {
		contentBase64 = *input.ContentBase64
	}
	sourceType := ""
	if input.SourceType != nil {
		sourceType = string(*input.SourceType)
	}

	result, err := r.RAGClient.CommitDocument(ctx, input.Title, content, metadata, sourceType, contentBase64)
	if err != nil {
		return nil, err
	}
	return &generated.CommitDocumentResult{
		Success: result.Success,
		Message: result.Message,
		ID:      result.ID,
	}, nil
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, id string) (*generated.DeleteDocumentResult, error) {
	success, message, err := r.RAGClient.DeleteDocument(ctx, id)
	if err != nil {
		return nil, err
	}
	return &generated.DeleteDocumentResult{Success: success, Message: message}, nil
}

// UpdateRagSetting is the resolver for the updateRagSetting field.
func (r *mutationResolver) UpdateRagSetting(ctx context.Context, key string, value string, changedBy *string) (*generated.UpdateSettingsResult, error) {
	changed := "admin"
	if changedBy != nil && *changedBy != "" {
		changed = *changedBy
	}
	result, err := r.RAGClient.UpdateRagSetting(ctx, key, value, changed)
	if err != nil {
		return nil, err
	}
	return &generated.UpdateSettingsResult{
		Success: result.Success,
		Message: result.Message,
	}, nil
}

// RollbackDocument is the resolver for the rollbackDocument field.
func (r *mutationResolver) RollbackDocument(ctx context.Context, documentID string, versionID int, rollbackBy *string) (*generated.RollbackResult, error) {
	by := "admin"
	if rollbackBy != nil && *rollbackBy != "" {
		by = *rollbackBy
	}
	result, err := r.RAGClient.RollbackDocument(ctx, documentID, int32(versionID), by)
	if err != nil {
		return nil, err
	}
	return &generated.RollbackResult{
		Success:      result.Success,
		Message:      result.Message,
		NewVersionID: &result.NewVersionID,
	}, nil
}

// UpdateDocument is the resolver for the updateDocument field.
func (r *mutationResolver) UpdateDocument(ctx context.Context, id string, title string, content string, updatedBy *string) (*generated.UpdateDocumentResult, error) {
	by := "admin"
	if updatedBy != nil && *updatedBy != "" {
		by = *updatedBy
	}
	result, err := r.RAGClient.UpdateDocument(ctx, id, title, content, by)
	if err != nil {
		return nil, err
	}
	return &generated.UpdateDocumentResult{
		Success: result.Success,
		Message: result.Message,
	}, nil
}

// DiscoverLinks is the resolver for the discoverLinks field.
func (r *mutationResolver) DiscoverLinks(ctx context.Context, url string, maxDepth int) (*generated.DiscoverLinksResult, error) {
	result, err := r.RAGClient.DiscoverLinks(ctx, url, int32(maxDepth))
	if err != nil {
		return nil, err
	}
	return &generated.DiscoverLinksResult{
		Links: result.Links,
	}, nil
}

// ScrapeUrls is the resolver for the scrapeUrls field.
func (r *mutationResolver) ScrapeUrls(ctx context.Context, urls []string) (*generated.ScrapeUrlsResult, error) {
	result, err := r.RAGClient.ScrapeUrls(ctx, urls)
	if err != nil {
		return nil, err
	}
	texts := make([]*generated.ScrapedText, len(result.Texts))
	for i, t := range result.Texts {
		t := t
		texts[i] = &generated.ScrapedText{
			URL:  t.URL,
			Text: t.Text,
		}
	}
	return &generated.ScrapeUrlsResult{
		Texts: texts,
	}, nil
}

// AdminLogin is the resolver for the adminLogin field.
func (r *mutationResolver) AdminLogin(ctx context.Context, username string, password string) (*generated.AdminLoginResult, error) {
	result, err := r.RAGClient.AdminLogin(ctx, username, password)
	if err != nil {
		return nil, err
	}
	resp := &generated.AdminLoginResult{
		Token:     result.Token,
		ExpiresAt: result.ExpiresAt,
		Success:   result.Success,
		Message:   result.Message,
	}
	if result.Admin != nil {
		resp.Admin = &generated.AdminInfo{
			ID:       int(result.Admin.ID),
			Username: result.Admin.Username,
			Role:     result.Admin.Role,
		}
	}
	return resp, nil
}

// AdminLogout is the resolver for the adminLogout field.
func (r *mutationResolver) AdminLogout(ctx context.Context, token string) (*generated.AdminLogoutResult, error) {
	result, err := r.RAGClient.AdminLogout(ctx, token)
	if err != nil {
		return nil, err
	}
	return &generated.AdminLogoutResult{
		Success: result.Success,
		Message: result.Message,
	}, nil
}

// AddAdmin is the resolver for the addAdmin field.
func (r *mutationResolver) AddAdmin(ctx context.Context, token string, username string, password string) (*generated.AddAdminResult, error) {
	result, err := r.RAGClient.AddAdmin(ctx, token, username, password)
	if err != nil {
		return nil, err
	}
	resp := &generated.AddAdminResult{
		Success: result.Success,
		Message: result.Message,
	}
	if result.Admin != nil {
		resp.Admin = &generated.AdminInfo{
			ID:       int(result.Admin.ID),
			Username: result.Admin.Username,
			Role:     result.Admin.Role,
		}
	}
	return resp, nil
}

// RemoveAdmin is the resolver for the removeAdmin field.
func (r *mutationResolver) RemoveAdmin(ctx context.Context, token string, adminID int) (*generated.RemoveAdminResult, error) {
	result, err := r.RAGClient.RemoveAdmin(ctx, token, int32(adminID))
	if err != nil {
		return nil, err
	}
	return &generated.RemoveAdminResult{
		Success: result.Success,
		Message: result.Message,
	}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
