package app

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"graphql-gateway/internal/app/generated"
	"graphql-gateway/internal/clients"
)

// AddDocument is the resolver for the addDocument field.
func (r *mutationResolver) AddDocument(ctx context.Context, input generated.AddDocumentInput) (*generated.AddDocumentResult, error) {
	metadata := make([]clients.MetadataEntry, len(input.Metadata))
	for i, m := range input.Metadata {
		metadata[i] = clients.MetadataEntry{Key: m.Key, Value: m.Value}
	}

	success, message, err := r.RAGClient.AddDocument(ctx, input.Title, input.Content, metadata)
	if err != nil {
		return nil, err
	}
	return &generated.AddDocumentResult{Success: success, Message: message}, nil
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, id string) (*generated.DeleteDocumentResult, error) {
	success, message, err := r.RAGClient.DeleteDocument(ctx, id)
	if err != nil {
		return nil, err
	}
	return &generated.DeleteDocumentResult{Success: success, Message: message}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
