package app

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"graphql-gateway/internal/app/generated"
	"graphql-gateway/internal/clients"
)

// PreviewDocument is the resolver for the previewDocument field.
func (r *mutationResolver) PreviewDocument(ctx context.Context, input generated.PreviewDocumentInput) (*generated.PreviewDocumentResult, error) {
	sourceURL := ""
	if input.SourceURL != nil {
		sourceURL = *input.SourceURL
	}
	contentBase64 := ""
	if input.ContentBase64 != nil {
		contentBase64 = *input.ContentBase64
	}
	urlMaxDepth := int32(0)
	if input.URLMaxDepth != nil {
		urlMaxDepth = int32(*input.URLMaxDepth)
	}

	result, err := r.RAGClient.PreviewDocument(
		ctx,
		input.Title,
		clients.MapDocumentSourceType(string(input.SourceType)),
		sourceURL,
		contentBase64,
		urlMaxDepth,
	)
	if err != nil {
		return nil, err
	}
	return &generated.PreviewDocumentResult{
		ExtractedText:  result.ExtractedText,
		PagesExtracted: int(result.PagesExtracted),
	}, nil
}

// CommitDocument is the resolver for the commitDocument field.
func (r *mutationResolver) CommitDocument(ctx context.Context, input generated.CommitDocumentInput) (*generated.CommitDocumentResult, error) {
	metadata := make([]clients.MetadataEntry, len(input.Metadata))
	for i, m := range input.Metadata {
		metadata[i] = clients.MetadataEntry{Key: m.Key, Value: m.Value}
	}

	result, err := r.RAGClient.CommitDocument(ctx, input.Title, input.Content, metadata)
	if err != nil {
		return nil, err
	}
	return &generated.CommitDocumentResult{
		Success: result.Success,
		Message: result.Message,
		ID:      result.ID,
	}, nil
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, id string) (*generated.DeleteDocumentResult, error) {
	success, message, err := r.RAGClient.DeleteDocument(ctx, id)
	if err != nil {
		return nil, err
	}
	return &generated.DeleteDocumentResult{Success: success, Message: message}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
