package app

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"graphql-gateway/internal/app/generated"
)

// Ask is the resolver for the ask field.
func (r *queryResolver) Ask(ctx context.Context, question string) (string, error) {
	return r.LLMClient.Ask(ctx, question)
}

// SearchDocuments is the resolver for the searchDocuments field.
func (r *queryResolver) SearchDocuments(ctx context.Context, query string, limit *int, threshold *float64) ([]*generated.DocumentResult, error) {
	l := int32(10)
	if limit != nil {
		l = int32(*limit)
	}
	t := float32(0.0)
	if threshold != nil {
		t = float32(*threshold)
	}

	results, _, err := r.RAGClient.SearchDocuments(ctx, query, l, t)
	if err != nil {
		return nil, err
	}

	docResults := make([]*generated.DocumentResult, len(results))
	for i, res := range results {
		meta := make([]*generated.MetadataEntry, len(res.Metadata))
		for j, m := range res.Metadata {
			meta[j] = &generated.MetadataEntry{Key: m.Key, Value: m.Value}
		}
		docResults[i] = &generated.DocumentResult{
			ID:              res.ID,
			Title:           res.Title,
			Content:         res.Content,
			SimilarityScore: float64(res.SimilarityScore),
			Metadata:        meta,
		}
	}
	return docResults, nil
}

// GetDocument is the resolver for the getDocument field.
func (r *queryResolver) GetDocument(ctx context.Context, id string) (*generated.Document, error) {
	doc, found, err := r.RAGClient.GetDocument(ctx, id)
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, nil
	}

	meta := make([]*generated.MetadataEntry, len(doc.Metadata))
	for j, m := range doc.Metadata {
		meta[j] = &generated.MetadataEntry{Key: m.Key, Value: m.Value}
	}
	return &generated.Document{
		ID:       doc.ID,
		Title:    doc.Title,
		Content:  doc.Content,
		Metadata: meta,
	}, nil
}

// GetIndexStats is the resolver for the getIndexStats field.
func (r *queryResolver) GetIndexStats(ctx context.Context) (*generated.IndexStats, error) {
	stats, err := r.RAGClient.GetIndexStats(ctx)
	if err != nil {
		return nil, err
	}
	return &generated.IndexStats{
		TotalDocuments: int(stats.TotalDocuments),
		IndexSizeBytes: int(stats.IndexSizeBytes),
		LastUpdated:    stats.LastUpdated,
	}, nil
}

// GetRagSettings is the resolver for the getRagSettings field.
func (r *queryResolver) GetRagSettings(ctx context.Context) ([]*generated.SettingEntry, error) {
	settings, err := r.RAGClient.GetRagSettings(ctx)
	if err != nil {
		return nil, err
	}
	entries := make([]*generated.SettingEntry, 0, len(settings))
	for k, v := range settings {
		entries = append(entries, &generated.SettingEntry{Key: k, Value: v})
	}
	return entries, nil
}

// GetRagSettingsHistory is the resolver for the getRagSettingsHistory field.
func (r *queryResolver) GetRagSettingsHistory(ctx context.Context, limit *int) ([]*generated.SettingsHistoryEntry, error) {
	l := int32(20)
	if limit != nil {
		l = int32(*limit)
	}
	history, err := r.RAGClient.GetRagSettingsHistory(ctx, l)
	if err != nil {
		return nil, err
	}
	entries := make([]*generated.SettingsHistoryEntry, 0, len(history))
	for _, h := range history {
		entries = append(entries, &generated.SettingsHistoryEntry{
			ID:         int(h.Id),
			SettingKey: h.SettingKey,
			OldValue:   h.OldValue,
			NewValue:   h.NewValue,
			ChangedBy:  h.ChangedBy,
		})
	}
	return entries, nil
}

// GetDocumentHistory is the resolver for the getDocumentHistory field.
func (r *queryResolver) GetDocumentHistory(ctx context.Context, documentID string, limit *int) ([]*generated.DocumentVersion, error) {
	l := int32(20)
	if limit != nil {
		l = int32(*limit)
	}
	versions, err := r.RAGClient.GetDocumentHistory(ctx, documentID, l)
	if err != nil {
		return nil, err
	}
	result := make([]*generated.DocumentVersion, 0, len(versions))
	for _, v := range versions {
		result = append(result, &generated.DocumentVersion{
			ID:            int(v.ID),
			DocumentID:    v.DocumentID,
			Title:         v.Title,
			Content:       v.Content,
			VersionNumber: int(v.VersionNumber),
			CreatedAt:     v.CreatedAt,
			CreatedBy:     v.CreatedBy,
			Action:        v.Action,
		})
	}
	return result, nil
}

// GetDocuments is the resolver for the getDocuments field.
func (r *queryResolver) GetDocuments(ctx context.Context) ([]*generated.DocumentListItem, error) {
	docs, err := r.RAGClient.GetDocuments(ctx)
	if err != nil {
		return nil, err
	}
	result := make([]*generated.DocumentListItem, 0, len(docs))
	for _, d := range docs {
		result = append(result, &generated.DocumentListItem{
			ID:        d.ID,
			Title:     d.Title,
			UpdatedAt: d.UpdatedAt,
			Indexed:   d.Indexed,
			Size:      int(d.Size),
			Chunks:    int(d.Chunks),
		})
	}
	return result, nil
}

// GetQueryLogs is the resolver for the getQueryLogs field.
func (r *queryResolver) GetQueryLogs(ctx context.Context, page *int, pageSize *int) (*generated.QueryLogsResult, error) {
	p := int32(1)
	if page != nil {
		p = int32(*page)
	}
	ps := int32(20)
	if pageSize != nil {
		ps = int32(*pageSize)
	}

	result, err := r.RAGClient.GetQueryLogs(ctx, p, ps)
	if err != nil {
		return nil, err
	}

	logs := make([]*generated.QueryLogEntry, 0, len(result.Logs))
	for _, l := range result.Logs {
		logs = append(logs, &generated.QueryLogEntry{
			ID:             int(l.ID),
			QueryText:      l.QueryText,
			EmbeddingModel: l.EmbeddingModel,
			ResponseTimeMs: int(l.ResponseTimeMs),
			Found:          l.Found,
			ResultsCount:   int(l.ResultsCount),
			CreatedAt:      l.CreatedAt,
		})
	}
	return &generated.QueryLogsResult{
		Logs:     logs,
		Total:    int(result.Total),
		Page:     int(result.Page),
		PageSize: int(result.PageSize),
	}, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
