package app

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"graphql-gateway/internal/app/generated"
)

// Ask is the resolver for the ask field.
func (r *queryResolver) Ask(ctx context.Context, question string) (string, error) {
	return r.LLMClient.Ask(ctx, question)
}

// SearchDocuments is the resolver for the searchDocuments field.
func (r *queryResolver) SearchDocuments(ctx context.Context, query string, limit *int, threshold *float64) ([]*generated.DocumentResult, error) {
	l := int32(10)
	if limit != nil {
		l = int32(*limit)
	}
	t := float32(0.0)
	if threshold != nil {
		t = float32(*threshold)
	}

	results, _, err := r.RAGClient.SearchDocuments(ctx, query, l, t)
	if err != nil {
		return nil, err
	}

	docResults := make([]*generated.DocumentResult, len(results))
	for i, res := range results {
		meta := make([]*generated.MetadataEntry, len(res.Metadata))
		for j, m := range res.Metadata {
			meta[j] = &generated.MetadataEntry{Key: m.Key, Value: m.Value}
		}
		docResults[i] = &generated.DocumentResult{
			ID:              res.ID,
			Title:           res.Title,
			Content:         res.Content,
			SimilarityScore: float64(res.SimilarityScore),
			Metadata:        meta,
		}
	}
	return docResults, nil
}

// GetDocument is the resolver for the getDocument field.
func (r *queryResolver) GetDocument(ctx context.Context, id string) (*generated.Document, error) {
	doc, found, err := r.RAGClient.GetDocument(ctx, id)
	if err != nil {
		return nil, err
	}
	if !found {
		return nil, nil
	}

	meta := make([]*generated.MetadataEntry, len(doc.Metadata))
	for j, m := range doc.Metadata {
		meta[j] = &generated.MetadataEntry{Key: m.Key, Value: m.Value}
	}
	return &generated.Document{
		ID:       doc.ID,
		Title:    doc.Title,
		Content:  doc.Content,
		Metadata: meta,
	}, nil
}

// GetIndexStats is the resolver for the getIndexStats field.
func (r *queryResolver) GetIndexStats(ctx context.Context) (*generated.IndexStats, error) {
	stats, err := r.RAGClient.GetIndexStats(ctx)
	if err != nil {
		return nil, err
	}
	return &generated.IndexStats{
		TotalDocuments: int(stats.TotalDocuments),
		IndexSizeBytes: int(stats.IndexSizeBytes),
		LastUpdated:    stats.LastUpdated,
	}, nil
}

// GetRagSettings is the resolver for the getRagSettings field.
func (r *queryResolver) GetRagSettings(ctx context.Context) ([]*generated.SettingEntry, error) {
	settings, err := r.RAGClient.GetRagSettings(ctx)
	if err != nil {
		return nil, err
	}
	entries := make([]*generated.SettingEntry, 0, len(settings))
	for k, v := range settings {
		entries = append(entries, &generated.SettingEntry{Key: k, Value: v})
	}
	return entries, nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
