// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/floatweaver.proto

package floatweaver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_api_floatweaver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_floatweaver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_api_floatweaver_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Embedding           `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_api_floatweaver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_floatweaver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_api_floatweaver_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedResponse) GetEmbeddings() []*Embedding {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type Embedding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Embedding) Reset() {
	*x = Embedding{}
	mi := &file_api_floatweaver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Embedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Embedding) ProtoMessage() {}

func (x *Embedding) ProtoReflect() protoreflect.Message {
	mi := &file_api_floatweaver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Embedding.ProtoReflect.Descriptor instead.
func (*Embedding) Descriptor() ([]byte, []int) {
	return file_api_floatweaver_proto_rawDescGZIP(), []int{2}
}

func (x *Embedding) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type SetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelRequest) Reset() {
	*x = SetModelRequest{}
	mi := &file_api_floatweaver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelRequest) ProtoMessage() {}

func (x *SetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_floatweaver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelRequest.ProtoReflect.Descriptor instead.
func (*SetModelRequest) Descriptor() ([]byte, []int) {
	return file_api_floatweaver_proto_rawDescGZIP(), []int{3}
}

func (x *SetModelRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type SetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetModelResponse) Reset() {
	*x = SetModelResponse{}
	mi := &file_api_floatweaver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetModelResponse) ProtoMessage() {}

func (x *SetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_floatweaver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetModelResponse.ProtoReflect.Descriptor instead.
func (*SetModelResponse) Descriptor() ([]byte, []int) {
	return file_api_floatweaver_proto_rawDescGZIP(), []int{4}
}

func (x *SetModelResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetModelResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetModelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_api_floatweaver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_floatweaver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_api_floatweaver_proto_rawDescGZIP(), []int{5}
}

type GetModelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Model         string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
	mi := &file_api_floatweaver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_floatweaver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResponse.ProtoReflect.Descriptor instead.
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return file_api_floatweaver_proto_rawDescGZIP(), []int{6}
}

func (x *GetModelResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_api_floatweaver_proto protoreflect.FileDescriptor

const file_api_floatweaver_proto_rawDesc = "" +
	"\n" +
	"\x15api/floatweaver.proto\x12\vfloatweaver\"\"\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"G\n" +
	"\rEmbedResponse\x126\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x16.floatweaver.EmbeddingR\n" +
	"embeddings\"#\n" +
	"\tEmbedding\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"'\n" +
	"\x0fSetModelRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\"F\n" +
	"\x10SetModelResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fGetModelRequest\"(\n" +
	"\x10GetModelResponse\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model2\xf8\x01\n" +
	"\fEmbedService\x12@\n" +
	"\x05Embed\x12\x19.floatweaver.EmbedRequest\x1a\x1a.floatweaver.EmbedResponse\"\x00\x12R\n" +
	"\x11SetEmbeddingModel\x12\x1c.floatweaver.SetModelRequest\x1a\x1d.floatweaver.SetModelResponse\"\x00\x12R\n" +
	"\x11GetEmbeddingModel\x12\x1c.floatweaver.GetModelRequest\x1a\x1d.floatweaver.GetModelResponse\"\x00B\x0fZ\r./floatweaverb\x06proto3"

var (
	file_api_floatweaver_proto_rawDescOnce sync.Once
	file_api_floatweaver_proto_rawDescData []byte
)

func file_api_floatweaver_proto_rawDescGZIP() []byte {
	file_api_floatweaver_proto_rawDescOnce.Do(func() {
		file_api_floatweaver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_floatweaver_proto_rawDesc), len(file_api_floatweaver_proto_rawDesc)))
	})
	return file_api_floatweaver_proto_rawDescData
}

var file_api_floatweaver_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_floatweaver_proto_goTypes = []any{
	(*EmbedRequest)(nil),     // 0: floatweaver.EmbedRequest
	(*EmbedResponse)(nil),    // 1: floatweaver.EmbedResponse
	(*Embedding)(nil),        // 2: floatweaver.Embedding
	(*SetModelRequest)(nil),  // 3: floatweaver.SetModelRequest
	(*SetModelResponse)(nil), // 4: floatweaver.SetModelResponse
	(*GetModelRequest)(nil),  // 5: floatweaver.GetModelRequest
	(*GetModelResponse)(nil), // 6: floatweaver.GetModelResponse
}
var file_api_floatweaver_proto_depIdxs = []int32{
	2, // 0: floatweaver.EmbedResponse.embeddings:type_name -> floatweaver.Embedding
	0, // 1: floatweaver.EmbedService.Embed:input_type -> floatweaver.EmbedRequest
	3, // 2: floatweaver.EmbedService.SetEmbeddingModel:input_type -> floatweaver.SetModelRequest
	5, // 3: floatweaver.EmbedService.GetEmbeddingModel:input_type -> floatweaver.GetModelRequest
	1, // 4: floatweaver.EmbedService.Embed:output_type -> floatweaver.EmbedResponse
	4, // 5: floatweaver.EmbedService.SetEmbeddingModel:output_type -> floatweaver.SetModelResponse
	6, // 6: floatweaver.EmbedService.GetEmbeddingModel:output_type -> floatweaver.GetModelResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_floatweaver_proto_init() }
func file_api_floatweaver_proto_init() {
	if File_api_floatweaver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_floatweaver_proto_rawDesc), len(file_api_floatweaver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_floatweaver_proto_goTypes,
		DependencyIndexes: file_api_floatweaver_proto_depIdxs,
		MessageInfos:      file_api_floatweaver_proto_msgTypes,
	}.Build()
	File_api_floatweaver_proto = out.File
	file_api_floatweaver_proto_goTypes = nil
	file_api_floatweaver_proto_depIdxs = nil
}
