// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/rag.proto

package rag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип источника документа
type DocumentSourceType int32

const (
	DocumentSourceType_SOURCE_TYPE_UNSPECIFIED DocumentSourceType = 0
	DocumentSourceType_SOURCE_TYPE_TEXT        DocumentSourceType = 1
	DocumentSourceType_SOURCE_TYPE_URL         DocumentSourceType = 2
	DocumentSourceType_SOURCE_TYPE_PDF         DocumentSourceType = 3
)

// Enum value maps for DocumentSourceType.
var (
	DocumentSourceType_name = map[int32]string{
		0: "SOURCE_TYPE_UNSPECIFIED",
		1: "SOURCE_TYPE_TEXT",
		2: "SOURCE_TYPE_URL",
		3: "SOURCE_TYPE_PDF",
	}
	DocumentSourceType_value = map[string]int32{
		"SOURCE_TYPE_UNSPECIFIED": 0,
		"SOURCE_TYPE_TEXT":        1,
		"SOURCE_TYPE_URL":         2,
		"SOURCE_TYPE_PDF":         3,
	}
)

func (x DocumentSourceType) Enum() *DocumentSourceType {
	p := new(DocumentSourceType)
	*p = x
	return p
}

func (x DocumentSourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentSourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rag_proto_enumTypes[0].Descriptor()
}

func (DocumentSourceType) Type() protoreflect.EnumType {
	return &file_api_rag_proto_enumTypes[0]
}

func (x DocumentSourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentSourceType.Descriptor instead.
func (DocumentSourceType) EnumDescriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{0}
}

// Тип метода сравнения векторов
type ComparisonMethod int32

const (
	ComparisonMethod_COMPARISON_METHOD_UNSPECIFIED ComparisonMethod = 0
	ComparisonMethod_COMPARISON_METHOD_COSINE      ComparisonMethod = 1 // Косинусное сходство
	ComparisonMethod_COMPARISON_METHOD_DOT         ComparisonMethod = 2 // Скалярное произведение
	ComparisonMethod_COMPARISON_METHOD_EUCLIDEAN   ComparisonMethod = 3 // Евклидово расстояние
	ComparisonMethod_COMPARISON_METHOD_L1          ComparisonMethod = 4 // Манхэттенское расстояние (L1)
)

// Enum value maps for ComparisonMethod.
var (
	ComparisonMethod_name = map[int32]string{
		0: "COMPARISON_METHOD_UNSPECIFIED",
		1: "COMPARISON_METHOD_COSINE",
		2: "COMPARISON_METHOD_DOT",
		3: "COMPARISON_METHOD_EUCLIDEAN",
		4: "COMPARISON_METHOD_L1",
	}
	ComparisonMethod_value = map[string]int32{
		"COMPARISON_METHOD_UNSPECIFIED": 0,
		"COMPARISON_METHOD_COSINE":      1,
		"COMPARISON_METHOD_DOT":         2,
		"COMPARISON_METHOD_EUCLIDEAN":   3,
		"COMPARISON_METHOD_L1":          4,
	}
)

func (x ComparisonMethod) Enum() *ComparisonMethod {
	p := new(ComparisonMethod)
	*p = x
	return p
}

func (x ComparisonMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComparisonMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rag_proto_enumTypes[1].Descriptor()
}

func (ComparisonMethod) Type() protoreflect.EnumType {
	return &file_api_rag_proto_enumTypes[1]
}

func (x ComparisonMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComparisonMethod.Descriptor instead.
func (ComparisonMethod) EnumDescriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{1}
}

// Запрос на добавление документа (legacy, для совместимости)
type AddDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,4,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SourceType    DocumentSourceType     `protobuf:"varint,6,opt,name=source_type,json=sourceType,proto3,enum=rag.DocumentSourceType" json:"source_type,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,7,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	UrlMaxDepth   int32                  `protobuf:"varint,8,opt,name=url_max_depth,json=urlMaxDepth,proto3" json:"url_max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocumentRequest) Reset() {
	*x = AddDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentRequest) ProtoMessage() {}

func (x *AddDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentRequest.ProtoReflect.Descriptor instead.
func (*AddDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{0}
}

func (x *AddDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddDocumentRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *AddDocumentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AddDocumentRequest) GetSourceType() DocumentSourceType {
	if x != nil {
		return x.SourceType
	}
	return DocumentSourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *AddDocumentRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *AddDocumentRequest) GetUrlMaxDepth() int32 {
	if x != nil {
		return x.UrlMaxDepth
	}
	return 0
}

// Ответ на добавление документа
type AddDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocumentResponse) Reset() {
	*x = AddDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentResponse) ProtoMessage() {}

func (x *AddDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentResponse.ProtoReflect.Descriptor instead.
func (*AddDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{1}
}

func (x *AddDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запрос на предпросмотр (извлечение текста без сохранения)
type PreviewDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	SourceType    DocumentSourceType     `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3,enum=rag.DocumentSourceType" json:"source_type,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	ContentBase64 string                 `protobuf:"bytes,4,opt,name=content_base64,json=contentBase64,proto3" json:"content_base64,omitempty"` // PDF as base64
	UrlMaxDepth   int32                  `protobuf:"varint,5,opt,name=url_max_depth,json=urlMaxDepth,proto3" json:"url_max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewDocumentRequest) Reset() {
	*x = PreviewDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewDocumentRequest) ProtoMessage() {}

func (x *PreviewDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewDocumentRequest.ProtoReflect.Descriptor instead.
func (*PreviewDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{2}
}

func (x *PreviewDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PreviewDocumentRequest) GetSourceType() DocumentSourceType {
	if x != nil {
		return x.SourceType
	}
	return DocumentSourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *PreviewDocumentRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *PreviewDocumentRequest) GetContentBase64() string {
	if x != nil {
		return x.ContentBase64
	}
	return ""
}

func (x *PreviewDocumentRequest) GetUrlMaxDepth() int32 {
	if x != nil {
		return x.UrlMaxDepth
	}
	return 0
}

// Ответ на предпросмотр
type PreviewDocumentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExtractedText  string                 `protobuf:"bytes,1,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"`
	PagesExtracted int32                  `protobuf:"varint,2,opt,name=pages_extracted,json=pagesExtracted,proto3" json:"pages_extracted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreviewDocumentResponse) Reset() {
	*x = PreviewDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewDocumentResponse) ProtoMessage() {}

func (x *PreviewDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewDocumentResponse.ProtoReflect.Descriptor instead.
func (*PreviewDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{3}
}

func (x *PreviewDocumentResponse) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

func (x *PreviewDocumentResponse) GetPagesExtracted() int32 {
	if x != nil {
		return x.PagesExtracted
	}
	return 0
}

// Запрос на коммит (сохранение отредактированного текста)
type CommitDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDocumentRequest) Reset() {
	*x = CommitDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDocumentRequest) ProtoMessage() {}

func (x *CommitDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDocumentRequest.ProtoReflect.Descriptor instead.
func (*CommitDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{4}
}

func (x *CommitDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CommitDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommitDocumentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Ответ на коммит
type CommitDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDocumentResponse) Reset() {
	*x = CommitDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDocumentResponse) ProtoMessage() {}

func (x *CommitDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDocumentResponse.ProtoReflect.Descriptor instead.
func (*CommitDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{5}
}

func (x *CommitDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitDocumentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Запрос на поиск документов
type SearchRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Query               string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit               int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SimilarityThreshold float32                `protobuf:"fixed32,3,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`
	ComparisonMethod    ComparisonMethod       `protobuf:"varint,4,opt,name=comparison_method,json=comparisonMethod,proto3,enum=rag.ComparisonMethod" json:"comparison_method,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetSimilarityThreshold() float32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

func (x *SearchRequest) GetComparisonMethod() ComparisonMethod {
	if x != nil {
		return x.ComparisonMethod
	}
	return ComparisonMethod_COMPARISON_METHOD_UNSPECIFIED
}

// Ответ на поиск документов
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DocumentResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalFound    int32                  `protobuf:"varint,2,opt,name=total_found,json=totalFound,proto3" json:"total_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetResults() []*DocumentResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotalFound() int32 {
	if x != nil {
		return x.TotalFound
	}
	return 0
}

// Результат поиска документа
type DocumentResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SimilarityScore float32                `protobuf:"fixed32,4,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentResult) Reset() {
	*x = DocumentResult{}
	mi := &file_api_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResult) ProtoMessage() {}

func (x *DocumentResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResult.ProtoReflect.Descriptor instead.
func (*DocumentResult) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{8}
}

func (x *DocumentResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentResult) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *DocumentResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Запрос на получение документа
type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{9}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ с документом
type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *DocumentResult        `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{10}
}

func (x *GetDocumentResponse) GetDocument() *DocumentResult {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *GetDocumentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Запрос на удаление документа
type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ на удаление документа
type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запрос статистики индекса
type GetIndexStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexStatsRequest) Reset() {
	*x = GetIndexStatsRequest{}
	mi := &file_api_rag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexStatsRequest) ProtoMessage() {}

func (x *GetIndexStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexStatsRequest.ProtoReflect.Descriptor instead.
func (*GetIndexStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{13}
}

// Ответ со статистикой индекса
type GetIndexStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalDocuments int32                  `protobuf:"varint,1,opt,name=total_documents,json=totalDocuments,proto3" json:"total_documents,omitempty"`
	IndexSizeBytes int64                  `protobuf:"varint,2,opt,name=index_size_bytes,json=indexSizeBytes,proto3" json:"index_size_bytes,omitempty"`
	LastUpdated    string                 `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetIndexStatsResponse) Reset() {
	*x = GetIndexStatsResponse{}
	mi := &file_api_rag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexStatsResponse) ProtoMessage() {}

func (x *GetIndexStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexStatsResponse.ProtoReflect.Descriptor instead.
func (*GetIndexStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{14}
}

func (x *GetIndexStatsResponse) GetTotalDocuments() int32 {
	if x != nil {
		return x.TotalDocuments
	}
	return 0
}

func (x *GetIndexStatsResponse) GetIndexSizeBytes() int64 {
	if x != nil {
		return x.IndexSizeBytes
	}
	return 0
}

func (x *GetIndexStatsResponse) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

// Запрос на получение настроек RAG
type GetRagSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRagSettingsRequest) Reset() {
	*x = GetRagSettingsRequest{}
	mi := &file_api_rag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRagSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRagSettingsRequest) ProtoMessage() {}

func (x *GetRagSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRagSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetRagSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{15}
}

// Ответ с настройками RAG
type GetRagSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      map[string]string      `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRagSettingsResponse) Reset() {
	*x = GetRagSettingsResponse{}
	mi := &file_api_rag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRagSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRagSettingsResponse) ProtoMessage() {}

func (x *GetRagSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRagSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetRagSettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{16}
}

func (x *GetRagSettingsResponse) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Запрос на обновление настройки RAG
type UpdateRagSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	ChangedBy     string                 `protobuf:"bytes,3,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRagSettingsRequest) Reset() {
	*x = UpdateRagSettingsRequest{}
	mi := &file_api_rag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRagSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRagSettingsRequest) ProtoMessage() {}

func (x *UpdateRagSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRagSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateRagSettingsRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateRagSettingsRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateRagSettingsRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateRagSettingsRequest) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

// Ответ на обновление настройки
type UpdateRagSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRagSettingsResponse) Reset() {
	*x = UpdateRagSettingsResponse{}
	mi := &file_api_rag_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRagSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRagSettingsResponse) ProtoMessage() {}

func (x *UpdateRagSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRagSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateRagSettingsResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateRagSettingsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRagSettingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запрос на получение истории настроек
type GetRagSettingsHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRagSettingsHistoryRequest) Reset() {
	*x = GetRagSettingsHistoryRequest{}
	mi := &file_api_rag_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRagSettingsHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRagSettingsHistoryRequest) ProtoMessage() {}

func (x *GetRagSettingsHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRagSettingsHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetRagSettingsHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{19}
}

func (x *GetRagSettingsHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Ответ с историей настроек
type GetRagSettingsHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Entries       []*SettingsHistoryEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRagSettingsHistoryResponse) Reset() {
	*x = GetRagSettingsHistoryResponse{}
	mi := &file_api_rag_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRagSettingsHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRagSettingsHistoryResponse) ProtoMessage() {}

func (x *GetRagSettingsHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRagSettingsHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetRagSettingsHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{20}
}

func (x *GetRagSettingsHistoryResponse) GetEntries() []*SettingsHistoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Запись истории изменения настройки
type SettingsHistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SettingKey    string                 `protobuf:"bytes,2,opt,name=setting_key,json=settingKey,proto3" json:"setting_key,omitempty"`
	OldValue      string                 `protobuf:"bytes,3,opt,name=old_value,json=oldValue,proto3" json:"old_value,omitempty"`
	NewValue      string                 `protobuf:"bytes,4,opt,name=new_value,json=newValue,proto3" json:"new_value,omitempty"`
	ChangedBy     string                 `protobuf:"bytes,5,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	ChangedAt     string                 `protobuf:"bytes,6,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsHistoryEntry) Reset() {
	*x = SettingsHistoryEntry{}
	mi := &file_api_rag_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsHistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsHistoryEntry) ProtoMessage() {}

func (x *SettingsHistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsHistoryEntry.ProtoReflect.Descriptor instead.
func (*SettingsHistoryEntry) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{21}
}

func (x *SettingsHistoryEntry) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SettingsHistoryEntry) GetSettingKey() string {
	if x != nil {
		return x.SettingKey
	}
	return ""
}

func (x *SettingsHistoryEntry) GetOldValue() string {
	if x != nil {
		return x.OldValue
	}
	return ""
}

func (x *SettingsHistoryEntry) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

func (x *SettingsHistoryEntry) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *SettingsHistoryEntry) GetChangedAt() string {
	if x != nil {
		return x.ChangedAt
	}
	return ""
}

// Запрос на получение истории версий документа
type GetDocumentHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentHistoryRequest) Reset() {
	*x = GetDocumentHistoryRequest{}
	mi := &file_api_rag_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentHistoryRequest) ProtoMessage() {}

func (x *GetDocumentHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{22}
}

func (x *GetDocumentHistoryRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetDocumentHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Ответ с историей версий документа
type GetDocumentHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*DocumentVersion     `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentHistoryResponse) Reset() {
	*x = GetDocumentHistoryResponse{}
	mi := &file_api_rag_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentHistoryResponse) ProtoMessage() {}

func (x *GetDocumentHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{23}
}

func (x *GetDocumentHistoryResponse) GetVersions() []*DocumentVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

// Версия документа
type DocumentVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	VersionNumber int32                  `protobuf:"varint,5,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Action        string                 `protobuf:"bytes,8,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentVersion) Reset() {
	*x = DocumentVersion{}
	mi := &file_api_rag_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentVersion) ProtoMessage() {}

func (x *DocumentVersion) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentVersion.ProtoReflect.Descriptor instead.
func (*DocumentVersion) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{24}
}

func (x *DocumentVersion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DocumentVersion) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentVersion) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentVersion) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentVersion) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *DocumentVersion) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DocumentVersion) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *DocumentVersion) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// Запрос на откат документа к версии
type RollbackDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	VersionId     int32                  `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	RollbackBy    string                 `protobuf:"bytes,3,opt,name=rollback_by,json=rollbackBy,proto3" json:"rollback_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackDocumentRequest) Reset() {
	*x = RollbackDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackDocumentRequest) ProtoMessage() {}

func (x *RollbackDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackDocumentRequest.ProtoReflect.Descriptor instead.
func (*RollbackDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{25}
}

func (x *RollbackDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RollbackDocumentRequest) GetVersionId() int32 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *RollbackDocumentRequest) GetRollbackBy() string {
	if x != nil {
		return x.RollbackBy
	}
	return ""
}

// Ответ на откат документа
type RollbackDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NewVersionId  string                 `protobuf:"bytes,3,opt,name=new_version_id,json=newVersionId,proto3" json:"new_version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackDocumentResponse) Reset() {
	*x = RollbackDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackDocumentResponse) ProtoMessage() {}

func (x *RollbackDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackDocumentResponse.ProtoReflect.Descriptor instead.
func (*RollbackDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{26}
}

func (x *RollbackDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RollbackDocumentResponse) GetNewVersionId() string {
	if x != nil {
		return x.NewVersionId
	}
	return ""
}

// Запрос на получение списка всех документов
type GetAllDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDocumentsRequest) Reset() {
	*x = GetAllDocumentsRequest{}
	mi := &file_api_rag_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDocumentsRequest) ProtoMessage() {}

func (x *GetAllDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDocumentsRequest.ProtoReflect.Descriptor instead.
func (*GetAllDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{27}
}

// Ответ со списком документов
type GetAllDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*DocumentListItem    `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllDocumentsResponse) Reset() {
	*x = GetAllDocumentsResponse{}
	mi := &file_api_rag_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllDocumentsResponse) ProtoMessage() {}

func (x *GetAllDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllDocumentsResponse.ProtoReflect.Descriptor instead.
func (*GetAllDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{28}
}

func (x *GetAllDocumentsResponse) GetDocuments() []*DocumentListItem {
	if x != nil {
		return x.Documents
	}
	return nil
}

// Элемент списка документов
type DocumentListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Indexed       bool                   `protobuf:"varint,4,opt,name=indexed,proto3" json:"indexed,omitempty"`
	SizeBytes     int32                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Chunks        int32                  `protobuf:"varint,6,opt,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentListItem) Reset() {
	*x = DocumentListItem{}
	mi := &file_api_rag_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentListItem) ProtoMessage() {}

func (x *DocumentListItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentListItem.ProtoReflect.Descriptor instead.
func (*DocumentListItem) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{29}
}

func (x *DocumentListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentListItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentListItem) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *DocumentListItem) GetIndexed() bool {
	if x != nil {
		return x.Indexed
	}
	return false
}

func (x *DocumentListItem) GetSizeBytes() int32 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *DocumentListItem) GetChunks() int32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

// Запрос на получение логов запросов
type GetQueryLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryLogsRequest) Reset() {
	*x = GetQueryLogsRequest{}
	mi := &file_api_rag_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryLogsRequest) ProtoMessage() {}

func (x *GetQueryLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryLogsRequest.ProtoReflect.Descriptor instead.
func (*GetQueryLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{30}
}

func (x *GetQueryLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetQueryLogsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Ответ с логами запросов
type GetQueryLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*QueryLogEntry       `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueryLogsResponse) Reset() {
	*x = GetQueryLogsResponse{}
	mi := &file_api_rag_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueryLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueryLogsResponse) ProtoMessage() {}

func (x *GetQueryLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueryLogsResponse.ProtoReflect.Descriptor instead.
func (*GetQueryLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{31}
}

func (x *GetQueryLogsResponse) GetLogs() []*QueryLogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetQueryLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetQueryLogsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetQueryLogsResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Запись лога запроса
type QueryLogEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	QueryText      string                 `protobuf:"bytes,2,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	EmbeddingModel string                 `protobuf:"bytes,3,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"`
	ResponseTimeMs int32                  `protobuf:"varint,4,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Found          bool                   `protobuf:"varint,5,opt,name=found,proto3" json:"found,omitempty"`
	ResultsCount   int32                  `protobuf:"varint,6,opt,name=results_count,json=resultsCount,proto3" json:"results_count,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryLogEntry) Reset() {
	*x = QueryLogEntry{}
	mi := &file_api_rag_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryLogEntry) ProtoMessage() {}

func (x *QueryLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryLogEntry.ProtoReflect.Descriptor instead.
func (*QueryLogEntry) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{32}
}

func (x *QueryLogEntry) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QueryLogEntry) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *QueryLogEntry) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

func (x *QueryLogEntry) GetResponseTimeMs() int32 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *QueryLogEntry) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *QueryLogEntry) GetResultsCount() int32 {
	if x != nil {
		return x.ResultsCount
	}
	return 0
}

func (x *QueryLogEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Запрос на обнаружение ссылок
type DiscoverLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	MaxDepth      int32                  `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverLinksRequest) Reset() {
	*x = DiscoverLinksRequest{}
	mi := &file_api_rag_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverLinksRequest) ProtoMessage() {}

func (x *DiscoverLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverLinksRequest.ProtoReflect.Descriptor instead.
func (*DiscoverLinksRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{33}
}

func (x *DiscoverLinksRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DiscoverLinksRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

// Ответ со списком ссылок
type DiscoverLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []string               `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverLinksResponse) Reset() {
	*x = DiscoverLinksResponse{}
	mi := &file_api_rag_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverLinksResponse) ProtoMessage() {}

func (x *DiscoverLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverLinksResponse.ProtoReflect.Descriptor instead.
func (*DiscoverLinksResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{34}
}

func (x *DiscoverLinksResponse) GetLinks() []string {
	if x != nil {
		return x.Links
	}
	return nil
}

// Запрос на скрапинг URL
type ScrapeUrlsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeUrlsRequest) Reset() {
	*x = ScrapeUrlsRequest{}
	mi := &file_api_rag_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeUrlsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeUrlsRequest) ProtoMessage() {}

func (x *ScrapeUrlsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeUrlsRequest.ProtoReflect.Descriptor instead.
func (*ScrapeUrlsRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{35}
}

func (x *ScrapeUrlsRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

// Ответ с текстами
type ScrapeUrlsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []*ScrapedTextEntry    `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapeUrlsResponse) Reset() {
	*x = ScrapeUrlsResponse{}
	mi := &file_api_rag_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapeUrlsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapeUrlsResponse) ProtoMessage() {}

func (x *ScrapeUrlsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapeUrlsResponse.ProtoReflect.Descriptor instead.
func (*ScrapeUrlsResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{36}
}

func (x *ScrapeUrlsResponse) GetTexts() []*ScrapedTextEntry {
	if x != nil {
		return x.Texts
	}
	return nil
}

// Текст с отдельного URL
type ScrapedTextEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrapedTextEntry) Reset() {
	*x = ScrapedTextEntry{}
	mi := &file_api_rag_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrapedTextEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrapedTextEntry) ProtoMessage() {}

func (x *ScrapedTextEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrapedTextEntry.ProtoReflect.Descriptor instead.
func (*ScrapedTextEntry) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{37}
}

func (x *ScrapedTextEntry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ScrapedTextEntry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_api_rag_proto protoreflect.FileDescriptor

const file_api_rag_proto_rawDesc = "" +
	"\n" +
	"\rapi/rag.proto\x12\x03rag\"\xef\x02\n" +
	"\x12AddDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1c\n" +
	"\tembedding\x18\x04 \x03(\x02R\tembedding\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.rag.AddDocumentRequest.MetadataEntryR\bmetadata\x128\n" +
	"\vsource_type\x18\x06 \x01(\x0e2\x17.rag.DocumentSourceTypeR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_url\x18\a \x01(\tR\tsourceUrl\x12\"\n" +
	"\rurl_max_depth\x18\b \x01(\x05R\vurlMaxDepth\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x13AddDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd2\x01\n" +
	"\x16PreviewDocumentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x128\n" +
	"\vsource_type\x18\x02 \x01(\x0e2\x17.rag.DocumentSourceTypeR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_url\x18\x03 \x01(\tR\tsourceUrl\x12%\n" +
	"\x0econtent_base64\x18\x04 \x01(\tR\rcontentBase64\x12\"\n" +
	"\rurl_max_depth\x18\x05 \x01(\x05R\vurlMaxDepth\"i\n" +
	"\x17PreviewDocumentResponse\x12%\n" +
	"\x0eextracted_text\x18\x01 \x01(\tR\rextractedText\x12'\n" +
	"\x0fpages_extracted\x18\x02 \x01(\x05R\x0epagesExtracted\"\xca\x01\n" +
	"\x15CommitDocumentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.rag.CommitDocumentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x16CommitDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"\xb2\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x121\n" +
	"\x14similarity_threshold\x18\x03 \x01(\x02R\x13similarityThreshold\x12B\n" +
	"\x11comparison_method\x18\x04 \x01(\x0e2\x15.rag.ComparisonMethodR\x10comparisonMethod\"`\n" +
	"\x0eSearchResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.rag.DocumentResultR\aresults\x12\x1f\n" +
	"\vtotal_found\x18\x02 \x01(\x05R\n" +
	"totalFound\"\xf7\x01\n" +
	"\x0eDocumentResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12)\n" +
	"\x10similarity_score\x18\x04 \x01(\x02R\x0fsimilarityScore\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.rag.DocumentResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x13GetDocumentResponse\x12/\n" +
	"\bdocument\x18\x01 \x01(\v2\x13.rag.DocumentResultR\bdocument\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"'\n" +
	"\x15DeleteDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16DeleteDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14GetIndexStatsRequest\"\x8d\x01\n" +
	"\x15GetIndexStatsResponse\x12'\n" +
	"\x0ftotal_documents\x18\x01 \x01(\x05R\x0etotalDocuments\x12(\n" +
	"\x10index_size_bytes\x18\x02 \x01(\x03R\x0eindexSizeBytes\x12!\n" +
	"\flast_updated\x18\x03 \x01(\tR\vlastUpdated\"\x17\n" +
	"\x15GetRagSettingsRequest\"\x9c\x01\n" +
	"\x16GetRagSettingsResponse\x12E\n" +
	"\bsettings\x18\x01 \x03(\v2).rag.GetRagSettingsResponse.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x18UpdateRagSettingsRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x03 \x01(\tR\tchangedBy\"O\n" +
	"\x19UpdateRagSettingsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"4\n" +
	"\x1cGetRagSettingsHistoryRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"T\n" +
	"\x1dGetRagSettingsHistoryResponse\x123\n" +
	"\aentries\x18\x01 \x03(\v2\x19.rag.SettingsHistoryEntryR\aentries\"\xbf\x01\n" +
	"\x14SettingsHistoryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vsetting_key\x18\x02 \x01(\tR\n" +
	"settingKey\x12\x1b\n" +
	"\told_value\x18\x03 \x01(\tR\boldValue\x12\x1b\n" +
	"\tnew_value\x18\x04 \x01(\tR\bnewValue\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x05 \x01(\tR\tchangedBy\x12\x1d\n" +
	"\n" +
	"changed_at\x18\x06 \x01(\tR\tchangedAt\"R\n" +
	"\x19GetDocumentHistoryRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"N\n" +
	"\x1aGetDocumentHistoryResponse\x120\n" +
	"\bversions\x18\x01 \x03(\v2\x14.rag.DocumentVersionR\bversions\"\xef\x01\n" +
	"\x0fDocumentVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12%\n" +
	"\x0eversion_number\x18\x05 \x01(\x05R\rversionNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x12\x16\n" +
	"\x06action\x18\b \x01(\tR\x06action\"z\n" +
	"\x17RollbackDocumentRequest\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x05R\tversionId\x12\x1f\n" +
	"\vrollback_by\x18\x03 \x01(\tR\n" +
	"rollbackBy\"t\n" +
	"\x18RollbackDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x0enew_version_id\x18\x03 \x01(\tR\fnewVersionId\"\x18\n" +
	"\x16GetAllDocumentsRequest\"N\n" +
	"\x17GetAllDocumentsResponse\x123\n" +
	"\tdocuments\x18\x01 \x03(\v2\x15.rag.DocumentListItemR\tdocuments\"\xa8\x01\n" +
	"\x10DocumentListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\tR\tupdatedAt\x12\x18\n" +
	"\aindexed\x18\x04 \x01(\bR\aindexed\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x05R\tsizeBytes\x12\x16\n" +
	"\x06chunks\x18\x06 \x01(\x05R\x06chunks\"F\n" +
	"\x13GetQueryLogsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x85\x01\n" +
	"\x14GetQueryLogsResponse\x12&\n" +
	"\x04logs\x18\x01 \x03(\v2\x12.rag.QueryLogEntryR\x04logs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xeb\x01\n" +
	"\rQueryLogEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"query_text\x18\x02 \x01(\tR\tqueryText\x12'\n" +
	"\x0fembedding_model\x18\x03 \x01(\tR\x0eembeddingModel\x12(\n" +
	"\x10response_time_ms\x18\x04 \x01(\x05R\x0eresponseTimeMs\x12\x14\n" +
	"\x05found\x18\x05 \x01(\bR\x05found\x12#\n" +
	"\rresults_count\x18\x06 \x01(\x05R\fresultsCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"E\n" +
	"\x14DiscoverLinksRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepth\"-\n" +
	"\x15DiscoverLinksResponse\x12\x14\n" +
	"\x05links\x18\x01 \x03(\tR\x05links\"'\n" +
	"\x11ScrapeUrlsRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls\"A\n" +
	"\x12ScrapeUrlsResponse\x12+\n" +
	"\x05texts\x18\x01 \x03(\v2\x15.rag.ScrapedTextEntryR\x05texts\"8\n" +
	"\x10ScrapedTextEntry\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text*q\n" +
	"\x12DocumentSourceType\x12\x1b\n" +
	"\x17SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SOURCE_TYPE_TEXT\x10\x01\x12\x13\n" +
	"\x0fSOURCE_TYPE_URL\x10\x02\x12\x13\n" +
	"\x0fSOURCE_TYPE_PDF\x10\x03*\xa9\x01\n" +
	"\x10ComparisonMethod\x12!\n" +
	"\x1dCOMPARISON_METHOD_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18COMPARISON_METHOD_COSINE\x10\x01\x12\x19\n" +
	"\x15COMPARISON_METHOD_DOT\x10\x02\x12\x1f\n" +
	"\x1bCOMPARISON_METHOD_EUCLIDEAN\x10\x03\x12\x18\n" +
	"\x14COMPARISON_METHOD_L1\x10\x042\xf7\b\n" +
	"\n" +
	"RagService\x12L\n" +
	"\x0fPreviewDocument\x12\x1b.rag.PreviewDocumentRequest\x1a\x1c.rag.PreviewDocumentResponse\x12I\n" +
	"\x0eCommitDocument\x12\x1a.rag.CommitDocumentRequest\x1a\x1b.rag.CommitDocumentResponse\x12:\n" +
	"\x0fSearchDocuments\x12\x12.rag.SearchRequest\x1a\x13.rag.SearchResponse\x12@\n" +
	"\vGetDocument\x12\x17.rag.GetDocumentRequest\x1a\x18.rag.GetDocumentResponse\x12I\n" +
	"\x0eDeleteDocument\x12\x1a.rag.DeleteDocumentRequest\x1a\x1b.rag.DeleteDocumentResponse\x12F\n" +
	"\rGetIndexStats\x12\x19.rag.GetIndexStatsRequest\x1a\x1a.rag.GetIndexStatsResponse\x12I\n" +
	"\x0eGetRagSettings\x12\x1a.rag.GetRagSettingsRequest\x1a\x1b.rag.GetRagSettingsResponse\x12R\n" +
	"\x11UpdateRagSettings\x12\x1d.rag.UpdateRagSettingsRequest\x1a\x1e.rag.UpdateRagSettingsResponse\x12^\n" +
	"\x15GetRagSettingsHistory\x12!.rag.GetRagSettingsHistoryRequest\x1a\".rag.GetRagSettingsHistoryResponse\x12U\n" +
	"\x12GetDocumentHistory\x12\x1e.rag.GetDocumentHistoryRequest\x1a\x1f.rag.GetDocumentHistoryResponse\x12O\n" +
	"\x10RollbackDocument\x12\x1c.rag.RollbackDocumentRequest\x1a\x1d.rag.RollbackDocumentResponse\x12L\n" +
	"\x0fGetAllDocuments\x12\x1b.rag.GetAllDocumentsRequest\x1a\x1c.rag.GetAllDocumentsResponse\x12C\n" +
	"\fGetQueryLogs\x12\x18.rag.GetQueryLogsRequest\x1a\x19.rag.GetQueryLogsResponse\x12F\n" +
	"\rDiscoverLinks\x12\x19.rag.DiscoverLinksRequest\x1a\x1a.rag.DiscoverLinksResponse\x12=\n" +
	"\n" +
	"ScrapeUrls\x12\x16.rag.ScrapeUrlsRequest\x1a\x17.rag.ScrapeUrlsResponseB\aZ\x05./ragb\x06proto3"

var (
	file_api_rag_proto_rawDescOnce sync.Once
	file_api_rag_proto_rawDescData []byte
)

func file_api_rag_proto_rawDescGZIP() []byte {
	file_api_rag_proto_rawDescOnce.Do(func() {
		file_api_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rag_proto_rawDesc), len(file_api_rag_proto_rawDesc)))
	})
	return file_api_rag_proto_rawDescData
}

var file_api_rag_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_api_rag_proto_goTypes = []any{
	(DocumentSourceType)(0),               // 0: rag.DocumentSourceType
	(ComparisonMethod)(0),                 // 1: rag.ComparisonMethod
	(*AddDocumentRequest)(nil),            // 2: rag.AddDocumentRequest
	(*AddDocumentResponse)(nil),           // 3: rag.AddDocumentResponse
	(*PreviewDocumentRequest)(nil),        // 4: rag.PreviewDocumentRequest
	(*PreviewDocumentResponse)(nil),       // 5: rag.PreviewDocumentResponse
	(*CommitDocumentRequest)(nil),         // 6: rag.CommitDocumentRequest
	(*CommitDocumentResponse)(nil),        // 7: rag.CommitDocumentResponse
	(*SearchRequest)(nil),                 // 8: rag.SearchRequest
	(*SearchResponse)(nil),                // 9: rag.SearchResponse
	(*DocumentResult)(nil),                // 10: rag.DocumentResult
	(*GetDocumentRequest)(nil),            // 11: rag.GetDocumentRequest
	(*GetDocumentResponse)(nil),           // 12: rag.GetDocumentResponse
	(*DeleteDocumentRequest)(nil),         // 13: rag.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),        // 14: rag.DeleteDocumentResponse
	(*GetIndexStatsRequest)(nil),          // 15: rag.GetIndexStatsRequest
	(*GetIndexStatsResponse)(nil),         // 16: rag.GetIndexStatsResponse
	(*GetRagSettingsRequest)(nil),         // 17: rag.GetRagSettingsRequest
	(*GetRagSettingsResponse)(nil),        // 18: rag.GetRagSettingsResponse
	(*UpdateRagSettingsRequest)(nil),      // 19: rag.UpdateRagSettingsRequest
	(*UpdateRagSettingsResponse)(nil),     // 20: rag.UpdateRagSettingsResponse
	(*GetRagSettingsHistoryRequest)(nil),  // 21: rag.GetRagSettingsHistoryRequest
	(*GetRagSettingsHistoryResponse)(nil), // 22: rag.GetRagSettingsHistoryResponse
	(*SettingsHistoryEntry)(nil),          // 23: rag.SettingsHistoryEntry
	(*GetDocumentHistoryRequest)(nil),     // 24: rag.GetDocumentHistoryRequest
	(*GetDocumentHistoryResponse)(nil),    // 25: rag.GetDocumentHistoryResponse
	(*DocumentVersion)(nil),               // 26: rag.DocumentVersion
	(*RollbackDocumentRequest)(nil),       // 27: rag.RollbackDocumentRequest
	(*RollbackDocumentResponse)(nil),      // 28: rag.RollbackDocumentResponse
	(*GetAllDocumentsRequest)(nil),        // 29: rag.GetAllDocumentsRequest
	(*GetAllDocumentsResponse)(nil),       // 30: rag.GetAllDocumentsResponse
	(*DocumentListItem)(nil),              // 31: rag.DocumentListItem
	(*GetQueryLogsRequest)(nil),           // 32: rag.GetQueryLogsRequest
	(*GetQueryLogsResponse)(nil),          // 33: rag.GetQueryLogsResponse
	(*QueryLogEntry)(nil),                 // 34: rag.QueryLogEntry
	(*DiscoverLinksRequest)(nil),          // 35: rag.DiscoverLinksRequest
	(*DiscoverLinksResponse)(nil),         // 36: rag.DiscoverLinksResponse
	(*ScrapeUrlsRequest)(nil),             // 37: rag.ScrapeUrlsRequest
	(*ScrapeUrlsResponse)(nil),            // 38: rag.ScrapeUrlsResponse
	(*ScrapedTextEntry)(nil),              // 39: rag.ScrapedTextEntry
	nil,                                   // 40: rag.AddDocumentRequest.MetadataEntry
	nil,                                   // 41: rag.CommitDocumentRequest.MetadataEntry
	nil,                                   // 42: rag.DocumentResult.MetadataEntry
	nil,                                   // 43: rag.GetRagSettingsResponse.SettingsEntry
}
var file_api_rag_proto_depIdxs = []int32{
	40, // 0: rag.AddDocumentRequest.metadata:type_name -> rag.AddDocumentRequest.MetadataEntry
	0,  // 1: rag.AddDocumentRequest.source_type:type_name -> rag.DocumentSourceType
	0,  // 2: rag.PreviewDocumentRequest.source_type:type_name -> rag.DocumentSourceType
	41, // 3: rag.CommitDocumentRequest.metadata:type_name -> rag.CommitDocumentRequest.MetadataEntry
	1,  // 4: rag.SearchRequest.comparison_method:type_name -> rag.ComparisonMethod
	10, // 5: rag.SearchResponse.results:type_name -> rag.DocumentResult
	42, // 6: rag.DocumentResult.metadata:type_name -> rag.DocumentResult.MetadataEntry
	10, // 7: rag.GetDocumentResponse.document:type_name -> rag.DocumentResult
	43, // 8: rag.GetRagSettingsResponse.settings:type_name -> rag.GetRagSettingsResponse.SettingsEntry
	23, // 9: rag.GetRagSettingsHistoryResponse.entries:type_name -> rag.SettingsHistoryEntry
	26, // 10: rag.GetDocumentHistoryResponse.versions:type_name -> rag.DocumentVersion
	31, // 11: rag.GetAllDocumentsResponse.documents:type_name -> rag.DocumentListItem
	34, // 12: rag.GetQueryLogsResponse.logs:type_name -> rag.QueryLogEntry
	39, // 13: rag.ScrapeUrlsResponse.texts:type_name -> rag.ScrapedTextEntry
	4,  // 14: rag.RagService.PreviewDocument:input_type -> rag.PreviewDocumentRequest
	6,  // 15: rag.RagService.CommitDocument:input_type -> rag.CommitDocumentRequest
	8,  // 16: rag.RagService.SearchDocuments:input_type -> rag.SearchRequest
	11, // 17: rag.RagService.GetDocument:input_type -> rag.GetDocumentRequest
	13, // 18: rag.RagService.DeleteDocument:input_type -> rag.DeleteDocumentRequest
	15, // 19: rag.RagService.GetIndexStats:input_type -> rag.GetIndexStatsRequest
	17, // 20: rag.RagService.GetRagSettings:input_type -> rag.GetRagSettingsRequest
	19, // 21: rag.RagService.UpdateRagSettings:input_type -> rag.UpdateRagSettingsRequest
	21, // 22: rag.RagService.GetRagSettingsHistory:input_type -> rag.GetRagSettingsHistoryRequest
	24, // 23: rag.RagService.GetDocumentHistory:input_type -> rag.GetDocumentHistoryRequest
	27, // 24: rag.RagService.RollbackDocument:input_type -> rag.RollbackDocumentRequest
	29, // 25: rag.RagService.GetAllDocuments:input_type -> rag.GetAllDocumentsRequest
	32, // 26: rag.RagService.GetQueryLogs:input_type -> rag.GetQueryLogsRequest
	35, // 27: rag.RagService.DiscoverLinks:input_type -> rag.DiscoverLinksRequest
	37, // 28: rag.RagService.ScrapeUrls:input_type -> rag.ScrapeUrlsRequest
	5,  // 29: rag.RagService.PreviewDocument:output_type -> rag.PreviewDocumentResponse
	7,  // 30: rag.RagService.CommitDocument:output_type -> rag.CommitDocumentResponse
	9,  // 31: rag.RagService.SearchDocuments:output_type -> rag.SearchResponse
	12, // 32: rag.RagService.GetDocument:output_type -> rag.GetDocumentResponse
	14, // 33: rag.RagService.DeleteDocument:output_type -> rag.DeleteDocumentResponse
	16, // 34: rag.RagService.GetIndexStats:output_type -> rag.GetIndexStatsResponse
	18, // 35: rag.RagService.GetRagSettings:output_type -> rag.GetRagSettingsResponse
	20, // 36: rag.RagService.UpdateRagSettings:output_type -> rag.UpdateRagSettingsResponse
	22, // 37: rag.RagService.GetRagSettingsHistory:output_type -> rag.GetRagSettingsHistoryResponse
	25, // 38: rag.RagService.GetDocumentHistory:output_type -> rag.GetDocumentHistoryResponse
	28, // 39: rag.RagService.RollbackDocument:output_type -> rag.RollbackDocumentResponse
	30, // 40: rag.RagService.GetAllDocuments:output_type -> rag.GetAllDocumentsResponse
	33, // 41: rag.RagService.GetQueryLogs:output_type -> rag.GetQueryLogsResponse
	36, // 42: rag.RagService.DiscoverLinks:output_type -> rag.DiscoverLinksResponse
	38, // 43: rag.RagService.ScrapeUrls:output_type -> rag.ScrapeUrlsResponse
	29, // [29:44] is the sub-list for method output_type
	14, // [14:29] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_rag_proto_init() }
func file_api_rag_proto_init() {
	if File_api_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rag_proto_rawDesc), len(file_api_rag_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rag_proto_goTypes,
		DependencyIndexes: file_api_rag_proto_depIdxs,
		EnumInfos:         file_api_rag_proto_enumTypes,
		MessageInfos:      file_api_rag_proto_msgTypes,
	}.Build()
	File_api_rag_proto = out.File
	file_api_rag_proto_goTypes = nil
	file_api_rag_proto_depIdxs = nil
}
