// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/rag.proto

package rag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagService_PreviewDocument_FullMethodName       = "/rag.RagService/PreviewDocument"
	RagService_CommitDocument_FullMethodName        = "/rag.RagService/CommitDocument"
	RagService_SearchDocuments_FullMethodName       = "/rag.RagService/SearchDocuments"
	RagService_GetDocument_FullMethodName           = "/rag.RagService/GetDocument"
	RagService_DeleteDocument_FullMethodName        = "/rag.RagService/DeleteDocument"
	RagService_GetIndexStats_FullMethodName         = "/rag.RagService/GetIndexStats"
	RagService_GetRagSettings_FullMethodName        = "/rag.RagService/GetRagSettings"
	RagService_UpdateRagSettings_FullMethodName     = "/rag.RagService/UpdateRagSettings"
	RagService_GetRagSettingsHistory_FullMethodName = "/rag.RagService/GetRagSettingsHistory"
	RagService_GetDocumentHistory_FullMethodName    = "/rag.RagService/GetDocumentHistory"
	RagService_RollbackDocument_FullMethodName      = "/rag.RagService/RollbackDocument"
	RagService_GetAllDocuments_FullMethodName       = "/rag.RagService/GetAllDocuments"
	RagService_GetQueryLogs_FullMethodName          = "/rag.RagService/GetQueryLogs"
	RagService_DiscoverLinks_FullMethodName         = "/rag.RagService/DiscoverLinks"
	RagService_ScrapeUrls_FullMethodName            = "/rag.RagService/ScrapeUrls"
)

// RagServiceClient is the client API for RagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RAG сервис для работы с документами и поиском
type RagServiceClient interface {
	// Предпросмотр: извлечь текст из PDF/URL без сохранения
	PreviewDocument(ctx context.Context, in *PreviewDocumentRequest, opts ...grpc.CallOption) (*PreviewDocumentResponse, error)
	// Сохранить документ с готовым текстом
	CommitDocument(ctx context.Context, in *CommitDocumentRequest, opts ...grpc.CallOption) (*CommitDocumentResponse, error)
	// Поиск документов по запросу
	SearchDocuments(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Получить документ по ID
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error)
	// Удалить документ по ID
	DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error)
	// Получить статистику индекса
	GetIndexStats(ctx context.Context, in *GetIndexStatsRequest, opts ...grpc.CallOption) (*GetIndexStatsResponse, error)
	// Получить все настройки RAG
	GetRagSettings(ctx context.Context, in *GetRagSettingsRequest, opts ...grpc.CallOption) (*GetRagSettingsResponse, error)
	// Обновить настройку RAG
	UpdateRagSettings(ctx context.Context, in *UpdateRagSettingsRequest, opts ...grpc.CallOption) (*UpdateRagSettingsResponse, error)
	// Получить историю изменений настроек
	GetRagSettingsHistory(ctx context.Context, in *GetRagSettingsHistoryRequest, opts ...grpc.CallOption) (*GetRagSettingsHistoryResponse, error)
	// Получить историю версий документа
	GetDocumentHistory(ctx context.Context, in *GetDocumentHistoryRequest, opts ...grpc.CallOption) (*GetDocumentHistoryResponse, error)
	// Откатить документ к определённой версии
	RollbackDocument(ctx context.Context, in *RollbackDocumentRequest, opts ...grpc.CallOption) (*RollbackDocumentResponse, error)
	// Получить список всех документов
	GetAllDocuments(ctx context.Context, in *GetAllDocumentsRequest, opts ...grpc.CallOption) (*GetAllDocumentsResponse, error)
	// Получить логи запросов с пагинацией
	GetQueryLogs(ctx context.Context, in *GetQueryLogsRequest, opts ...grpc.CallOption) (*GetQueryLogsResponse, error)
	// Найти ссылки на странице (BFS)
	DiscoverLinks(ctx context.Context, in *DiscoverLinksRequest, opts ...grpc.CallOption) (*DiscoverLinksResponse, error)
	// Скрапить выбранные URL
	ScrapeUrls(ctx context.Context, in *ScrapeUrlsRequest, opts ...grpc.CallOption) (*ScrapeUrlsResponse, error)
}

type ragServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagServiceClient(cc grpc.ClientConnInterface) RagServiceClient {
	return &ragServiceClient{cc}
}

func (c *ragServiceClient) PreviewDocument(ctx context.Context, in *PreviewDocumentRequest, opts ...grpc.CallOption) (*PreviewDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewDocumentResponse)
	err := c.cc.Invoke(ctx, RagService_PreviewDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) CommitDocument(ctx context.Context, in *CommitDocumentRequest, opts ...grpc.CallOption) (*CommitDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitDocumentResponse)
	err := c.cc.Invoke(ctx, RagService_CommitDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) SearchDocuments(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, RagService_SearchDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*GetDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentResponse)
	err := c.cc.Invoke(ctx, RagService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) DeleteDocument(ctx context.Context, in *DeleteDocumentRequest, opts ...grpc.CallOption) (*DeleteDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocumentResponse)
	err := c.cc.Invoke(ctx, RagService_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetIndexStats(ctx context.Context, in *GetIndexStatsRequest, opts ...grpc.CallOption) (*GetIndexStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIndexStatsResponse)
	err := c.cc.Invoke(ctx, RagService_GetIndexStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetRagSettings(ctx context.Context, in *GetRagSettingsRequest, opts ...grpc.CallOption) (*GetRagSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRagSettingsResponse)
	err := c.cc.Invoke(ctx, RagService_GetRagSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) UpdateRagSettings(ctx context.Context, in *UpdateRagSettingsRequest, opts ...grpc.CallOption) (*UpdateRagSettingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRagSettingsResponse)
	err := c.cc.Invoke(ctx, RagService_UpdateRagSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetRagSettingsHistory(ctx context.Context, in *GetRagSettingsHistoryRequest, opts ...grpc.CallOption) (*GetRagSettingsHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRagSettingsHistoryResponse)
	err := c.cc.Invoke(ctx, RagService_GetRagSettingsHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetDocumentHistory(ctx context.Context, in *GetDocumentHistoryRequest, opts ...grpc.CallOption) (*GetDocumentHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocumentHistoryResponse)
	err := c.cc.Invoke(ctx, RagService_GetDocumentHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) RollbackDocument(ctx context.Context, in *RollbackDocumentRequest, opts ...grpc.CallOption) (*RollbackDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackDocumentResponse)
	err := c.cc.Invoke(ctx, RagService_RollbackDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetAllDocuments(ctx context.Context, in *GetAllDocumentsRequest, opts ...grpc.CallOption) (*GetAllDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllDocumentsResponse)
	err := c.cc.Invoke(ctx, RagService_GetAllDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetQueryLogs(ctx context.Context, in *GetQueryLogsRequest, opts ...grpc.CallOption) (*GetQueryLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueryLogsResponse)
	err := c.cc.Invoke(ctx, RagService_GetQueryLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) DiscoverLinks(ctx context.Context, in *DiscoverLinksRequest, opts ...grpc.CallOption) (*DiscoverLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverLinksResponse)
	err := c.cc.Invoke(ctx, RagService_DiscoverLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) ScrapeUrls(ctx context.Context, in *ScrapeUrlsRequest, opts ...grpc.CallOption) (*ScrapeUrlsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrapeUrlsResponse)
	err := c.cc.Invoke(ctx, RagService_ScrapeUrls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServiceServer is the server API for RagService service.
// All implementations must embed UnimplementedRagServiceServer
// for forward compatibility.
//
// RAG сервис для работы с документами и поиском
type RagServiceServer interface {
	// Предпросмотр: извлечь текст из PDF/URL без сохранения
	PreviewDocument(context.Context, *PreviewDocumentRequest) (*PreviewDocumentResponse, error)
	// Сохранить документ с готовым текстом
	CommitDocument(context.Context, *CommitDocumentRequest) (*CommitDocumentResponse, error)
	// Поиск документов по запросу
	SearchDocuments(context.Context, *SearchRequest) (*SearchResponse, error)
	// Получить документ по ID
	GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error)
	// Удалить документ по ID
	DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error)
	// Получить статистику индекса
	GetIndexStats(context.Context, *GetIndexStatsRequest) (*GetIndexStatsResponse, error)
	// Получить все настройки RAG
	GetRagSettings(context.Context, *GetRagSettingsRequest) (*GetRagSettingsResponse, error)
	// Обновить настройку RAG
	UpdateRagSettings(context.Context, *UpdateRagSettingsRequest) (*UpdateRagSettingsResponse, error)
	// Получить историю изменений настроек
	GetRagSettingsHistory(context.Context, *GetRagSettingsHistoryRequest) (*GetRagSettingsHistoryResponse, error)
	// Получить историю версий документа
	GetDocumentHistory(context.Context, *GetDocumentHistoryRequest) (*GetDocumentHistoryResponse, error)
	// Откатить документ к определённой версии
	RollbackDocument(context.Context, *RollbackDocumentRequest) (*RollbackDocumentResponse, error)
	// Получить список всех документов
	GetAllDocuments(context.Context, *GetAllDocumentsRequest) (*GetAllDocumentsResponse, error)
	// Получить логи запросов с пагинацией
	GetQueryLogs(context.Context, *GetQueryLogsRequest) (*GetQueryLogsResponse, error)
	// Найти ссылки на странице (BFS)
	DiscoverLinks(context.Context, *DiscoverLinksRequest) (*DiscoverLinksResponse, error)
	// Скрапить выбранные URL
	ScrapeUrls(context.Context, *ScrapeUrlsRequest) (*ScrapeUrlsResponse, error)
	mustEmbedUnimplementedRagServiceServer()
}

// UnimplementedRagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServiceServer struct{}

func (UnimplementedRagServiceServer) PreviewDocument(context.Context, *PreviewDocumentRequest) (*PreviewDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewDocument not implemented")
}
func (UnimplementedRagServiceServer) CommitDocument(context.Context, *CommitDocumentRequest) (*CommitDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitDocument not implemented")
}
func (UnimplementedRagServiceServer) SearchDocuments(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchDocuments not implemented")
}
func (UnimplementedRagServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*GetDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedRagServiceServer) DeleteDocument(context.Context, *DeleteDocumentRequest) (*DeleteDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedRagServiceServer) GetIndexStats(context.Context, *GetIndexStatsRequest) (*GetIndexStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndexStats not implemented")
}
func (UnimplementedRagServiceServer) GetRagSettings(context.Context, *GetRagSettingsRequest) (*GetRagSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRagSettings not implemented")
}
func (UnimplementedRagServiceServer) UpdateRagSettings(context.Context, *UpdateRagSettingsRequest) (*UpdateRagSettingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRagSettings not implemented")
}
func (UnimplementedRagServiceServer) GetRagSettingsHistory(context.Context, *GetRagSettingsHistoryRequest) (*GetRagSettingsHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRagSettingsHistory not implemented")
}
func (UnimplementedRagServiceServer) GetDocumentHistory(context.Context, *GetDocumentHistoryRequest) (*GetDocumentHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocumentHistory not implemented")
}
func (UnimplementedRagServiceServer) RollbackDocument(context.Context, *RollbackDocumentRequest) (*RollbackDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackDocument not implemented")
}
func (UnimplementedRagServiceServer) GetAllDocuments(context.Context, *GetAllDocumentsRequest) (*GetAllDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllDocuments not implemented")
}
func (UnimplementedRagServiceServer) GetQueryLogs(context.Context, *GetQueryLogsRequest) (*GetQueryLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueryLogs not implemented")
}
func (UnimplementedRagServiceServer) DiscoverLinks(context.Context, *DiscoverLinksRequest) (*DiscoverLinksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscoverLinks not implemented")
}
func (UnimplementedRagServiceServer) ScrapeUrls(context.Context, *ScrapeUrlsRequest) (*ScrapeUrlsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScrapeUrls not implemented")
}
func (UnimplementedRagServiceServer) mustEmbedUnimplementedRagServiceServer() {}
func (UnimplementedRagServiceServer) testEmbeddedByValue()                    {}

// UnsafeRagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServiceServer will
// result in compilation errors.
type UnsafeRagServiceServer interface {
	mustEmbedUnimplementedRagServiceServer()
}

func RegisterRagServiceServer(s grpc.ServiceRegistrar, srv RagServiceServer) {
	// If the following call panics, it indicates UnimplementedRagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagService_ServiceDesc, srv)
}

func _RagService_PreviewDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).PreviewDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_PreviewDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).PreviewDocument(ctx, req.(*PreviewDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_CommitDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).CommitDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_CommitDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).CommitDocument(ctx, req.(*CommitDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_SearchDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).SearchDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_SearchDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).SearchDocuments(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).DeleteDocument(ctx, req.(*DeleteDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetIndexStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetIndexStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetIndexStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetIndexStats(ctx, req.(*GetIndexStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetRagSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRagSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetRagSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetRagSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetRagSettings(ctx, req.(*GetRagSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_UpdateRagSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRagSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).UpdateRagSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_UpdateRagSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).UpdateRagSettings(ctx, req.(*UpdateRagSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetRagSettingsHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRagSettingsHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetRagSettingsHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetRagSettingsHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetRagSettingsHistory(ctx, req.(*GetRagSettingsHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetDocumentHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetDocumentHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetDocumentHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetDocumentHistory(ctx, req.(*GetDocumentHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_RollbackDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).RollbackDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_RollbackDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).RollbackDocument(ctx, req.(*RollbackDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetAllDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetAllDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetAllDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetAllDocuments(ctx, req.(*GetAllDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetQueryLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueryLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetQueryLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetQueryLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetQueryLogs(ctx, req.(*GetQueryLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_DiscoverLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).DiscoverLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_DiscoverLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).DiscoverLinks(ctx, req.(*DiscoverLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_ScrapeUrls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrapeUrlsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).ScrapeUrls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_ScrapeUrls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).ScrapeUrls(ctx, req.(*ScrapeUrlsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RagService_ServiceDesc is the grpc.ServiceDesc for RagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.RagService",
	HandlerType: (*RagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PreviewDocument",
			Handler:    _RagService_PreviewDocument_Handler,
		},
		{
			MethodName: "CommitDocument",
			Handler:    _RagService_CommitDocument_Handler,
		},
		{
			MethodName: "SearchDocuments",
			Handler:    _RagService_SearchDocuments_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _RagService_GetDocument_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _RagService_DeleteDocument_Handler,
		},
		{
			MethodName: "GetIndexStats",
			Handler:    _RagService_GetIndexStats_Handler,
		},
		{
			MethodName: "GetRagSettings",
			Handler:    _RagService_GetRagSettings_Handler,
		},
		{
			MethodName: "UpdateRagSettings",
			Handler:    _RagService_UpdateRagSettings_Handler,
		},
		{
			MethodName: "GetRagSettingsHistory",
			Handler:    _RagService_GetRagSettingsHistory_Handler,
		},
		{
			MethodName: "GetDocumentHistory",
			Handler:    _RagService_GetDocumentHistory_Handler,
		},
		{
			MethodName: "RollbackDocument",
			Handler:    _RagService_RollbackDocument_Handler,
		},
		{
			MethodName: "GetAllDocuments",
			Handler:    _RagService_GetAllDocuments_Handler,
		},
		{
			MethodName: "GetQueryLogs",
			Handler:    _RagService_GetQueryLogs_Handler,
		},
		{
			MethodName: "DiscoverLinks",
			Handler:    _RagService_DiscoverLinks_Handler,
		},
		{
			MethodName: "ScrapeUrls",
			Handler:    _RagService_ScrapeUrls_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rag.proto",
}
