services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    restart: always
    environment:
      - OLLAMA_MODELS=phi3:latest

volumes:
  ollama_data: 