// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/gateway.proto

package llm_gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskRequest) Reset() {
	*x = AskRequest{}
	mi := &file_api_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskRequest) ProtoMessage() {}

func (x *AskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskRequest.ProtoReflect.Descriptor instead.
func (*AskRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *AskRequest) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type AskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskResponse) Reset() {
	*x = AskResponse{}
	mi := &file_api_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskResponse) ProtoMessage() {}

func (x *AskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskResponse.ProtoReflect.Descriptor instead.
func (*AskResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *AskResponse) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

type UpdateBasePromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBasePromptRequest) Reset() {
	*x = UpdateBasePromptRequest{}
	mi := &file_api_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBasePromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasePromptRequest) ProtoMessage() {}

func (x *UpdateBasePromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasePromptRequest.ProtoReflect.Descriptor instead.
func (*UpdateBasePromptRequest) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateBasePromptRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type UpdateBasePromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBasePromptResponse) Reset() {
	*x = UpdateBasePromptResponse{}
	mi := &file_api_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBasePromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBasePromptResponse) ProtoMessage() {}

func (x *UpdateBasePromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBasePromptResponse.ProtoReflect.Descriptor instead.
func (*UpdateBasePromptResponse) Descriptor() ([]byte, []int) {
	return file_api_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateBasePromptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_gateway_proto protoreflect.FileDescriptor

const file_api_gateway_proto_rawDesc = "" +
	"\n" +
	"\x11api/gateway.proto\x12\agateway\"(\n" +
	"\n" +
	"AskRequest\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"%\n" +
	"\vAskResponse\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\"1\n" +
	"\x17UpdateBasePromptRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"4\n" +
	"\x18UpdateBasePromptResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x9f\x01\n" +
	"\x0eGatewayService\x122\n" +
	"\x03Ask\x12\x13.gateway.AskRequest\x1a\x14.gateway.AskResponse\"\x00\x12Y\n" +
	"\x10UpdateBasePrompt\x12 .gateway.UpdateBasePromptRequest\x1a!.gateway.UpdateBasePromptResponse\"\x00B\x0fZ\r./llm-gatewayb\x06proto3"

var (
	file_api_gateway_proto_rawDescOnce sync.Once
	file_api_gateway_proto_rawDescData []byte
)

func file_api_gateway_proto_rawDescGZIP() []byte {
	file_api_gateway_proto_rawDescOnce.Do(func() {
		file_api_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gateway_proto_rawDesc), len(file_api_gateway_proto_rawDesc)))
	})
	return file_api_gateway_proto_rawDescData
}

var file_api_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_gateway_proto_goTypes = []any{
	(*AskRequest)(nil),               // 0: gateway.AskRequest
	(*AskResponse)(nil),              // 1: gateway.AskResponse
	(*UpdateBasePromptRequest)(nil),  // 2: gateway.UpdateBasePromptRequest
	(*UpdateBasePromptResponse)(nil), // 3: gateway.UpdateBasePromptResponse
}
var file_api_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayService.Ask:input_type -> gateway.AskRequest
	2, // 1: gateway.GatewayService.UpdateBasePrompt:input_type -> gateway.UpdateBasePromptRequest
	1, // 2: gateway.GatewayService.Ask:output_type -> gateway.AskResponse
	3, // 3: gateway.GatewayService.UpdateBasePrompt:output_type -> gateway.UpdateBasePromptResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_gateway_proto_init() }
func file_api_gateway_proto_init() {
	if File_api_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_proto_rawDesc), len(file_api_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_proto_goTypes,
		DependencyIndexes: file_api_gateway_proto_depIdxs,
		MessageInfos:      file_api_gateway_proto_msgTypes,
	}.Build()
	File_api_gateway_proto = out.File
	file_api_gateway_proto_goTypes = nil
	file_api_gateway_proto_depIdxs = nil
}
