services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: rag_postgres
    environment:
      POSTGRES_DB: rag_db
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag_user -d rag_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:latest
    container_name: rag_migrate
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://rag_user:rag_password@postgres:5432/rag_db?sslmode=disable
    volumes:
      - ./migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://rag_user:rag_password@postgres:5432/rag_db?sslmode=disable", "up"]

volumes:
  postgres_data: 