// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/rag.proto

package rag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип источника документа
type DocumentSourceType int32

const (
	DocumentSourceType_SOURCE_TYPE_UNSPECIFIED DocumentSourceType = 0
	DocumentSourceType_SOURCE_TYPE_TEXT        DocumentSourceType = 1
	DocumentSourceType_SOURCE_TYPE_URL         DocumentSourceType = 2
	DocumentSourceType_SOURCE_TYPE_PDF         DocumentSourceType = 3
)

// Enum value maps for DocumentSourceType.
var (
	DocumentSourceType_name = map[int32]string{
		0: "SOURCE_TYPE_UNSPECIFIED",
		1: "SOURCE_TYPE_TEXT",
		2: "SOURCE_TYPE_URL",
		3: "SOURCE_TYPE_PDF",
	}
	DocumentSourceType_value = map[string]int32{
		"SOURCE_TYPE_UNSPECIFIED": 0,
		"SOURCE_TYPE_TEXT":        1,
		"SOURCE_TYPE_URL":         2,
		"SOURCE_TYPE_PDF":         3,
	}
)

func (x DocumentSourceType) Enum() *DocumentSourceType {
	p := new(DocumentSourceType)
	*p = x
	return p
}

func (x DocumentSourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentSourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_rag_proto_enumTypes[0].Descriptor()
}

func (DocumentSourceType) Type() protoreflect.EnumType {
	return &file_api_rag_proto_enumTypes[0]
}

func (x DocumentSourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentSourceType.Descriptor instead.
func (DocumentSourceType) EnumDescriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{0}
}

// Запрос на добавление документа (legacy, для совместимости)
type AddDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Embedding     []float32              `protobuf:"fixed32,4,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SourceType    DocumentSourceType     `protobuf:"varint,6,opt,name=source_type,json=sourceType,proto3,enum=rag.DocumentSourceType" json:"source_type,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,7,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	UrlMaxDepth   int32                  `protobuf:"varint,8,opt,name=url_max_depth,json=urlMaxDepth,proto3" json:"url_max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocumentRequest) Reset() {
	*x = AddDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentRequest) ProtoMessage() {}

func (x *AddDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentRequest.ProtoReflect.Descriptor instead.
func (*AddDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{0}
}

func (x *AddDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AddDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AddDocumentRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *AddDocumentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AddDocumentRequest) GetSourceType() DocumentSourceType {
	if x != nil {
		return x.SourceType
	}
	return DocumentSourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *AddDocumentRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *AddDocumentRequest) GetUrlMaxDepth() int32 {
	if x != nil {
		return x.UrlMaxDepth
	}
	return 0
}

// Ответ на добавление документа
type AddDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocumentResponse) Reset() {
	*x = AddDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentResponse) ProtoMessage() {}

func (x *AddDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentResponse.ProtoReflect.Descriptor instead.
func (*AddDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{1}
}

func (x *AddDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запрос на предпросмотр (извлечение текста без сохранения)
type PreviewDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	SourceType    DocumentSourceType     `protobuf:"varint,2,opt,name=source_type,json=sourceType,proto3,enum=rag.DocumentSourceType" json:"source_type,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	ContentBase64 string                 `protobuf:"bytes,4,opt,name=content_base64,json=contentBase64,proto3" json:"content_base64,omitempty"` // PDF as base64
	UrlMaxDepth   int32                  `protobuf:"varint,5,opt,name=url_max_depth,json=urlMaxDepth,proto3" json:"url_max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewDocumentRequest) Reset() {
	*x = PreviewDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewDocumentRequest) ProtoMessage() {}

func (x *PreviewDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewDocumentRequest.ProtoReflect.Descriptor instead.
func (*PreviewDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{2}
}

func (x *PreviewDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PreviewDocumentRequest) GetSourceType() DocumentSourceType {
	if x != nil {
		return x.SourceType
	}
	return DocumentSourceType_SOURCE_TYPE_UNSPECIFIED
}

func (x *PreviewDocumentRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *PreviewDocumentRequest) GetContentBase64() string {
	if x != nil {
		return x.ContentBase64
	}
	return ""
}

func (x *PreviewDocumentRequest) GetUrlMaxDepth() int32 {
	if x != nil {
		return x.UrlMaxDepth
	}
	return 0
}

// Ответ на предпросмотр
type PreviewDocumentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExtractedText  string                 `protobuf:"bytes,1,opt,name=extracted_text,json=extractedText,proto3" json:"extracted_text,omitempty"`
	PagesExtracted int32                  `protobuf:"varint,2,opt,name=pages_extracted,json=pagesExtracted,proto3" json:"pages_extracted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreviewDocumentResponse) Reset() {
	*x = PreviewDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewDocumentResponse) ProtoMessage() {}

func (x *PreviewDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewDocumentResponse.ProtoReflect.Descriptor instead.
func (*PreviewDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{3}
}

func (x *PreviewDocumentResponse) GetExtractedText() string {
	if x != nil {
		return x.ExtractedText
	}
	return ""
}

func (x *PreviewDocumentResponse) GetPagesExtracted() int32 {
	if x != nil {
		return x.PagesExtracted
	}
	return 0
}

// Запрос на коммит (сохранение отредактированного текста)
type CommitDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDocumentRequest) Reset() {
	*x = CommitDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDocumentRequest) ProtoMessage() {}

func (x *CommitDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDocumentRequest.ProtoReflect.Descriptor instead.
func (*CommitDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{4}
}

func (x *CommitDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CommitDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CommitDocumentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Ответ на коммит
type CommitDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitDocumentResponse) Reset() {
	*x = CommitDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitDocumentResponse) ProtoMessage() {}

func (x *CommitDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitDocumentResponse.ProtoReflect.Descriptor instead.
func (*CommitDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{5}
}

func (x *CommitDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommitDocumentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Запрос на поиск документов
type SearchRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Query               string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit               int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SimilarityThreshold float32                `protobuf:"fixed32,3,opt,name=similarity_threshold,json=similarityThreshold,proto3" json:"similarity_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetSimilarityThreshold() float32 {
	if x != nil {
		return x.SimilarityThreshold
	}
	return 0
}

// Ответ на поиск документов
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DocumentResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	TotalFound    int32                  `protobuf:"varint,2,opt,name=total_found,json=totalFound,proto3" json:"total_found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetResults() []*DocumentResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetTotalFound() int32 {
	if x != nil {
		return x.TotalFound
	}
	return 0
}

// Результат поиска документа
type DocumentResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content         string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SimilarityScore float32                `protobuf:"fixed32,4,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DocumentResult) Reset() {
	*x = DocumentResult{}
	mi := &file_api_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentResult) ProtoMessage() {}

func (x *DocumentResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentResult.ProtoReflect.Descriptor instead.
func (*DocumentResult) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{8}
}

func (x *DocumentResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DocumentResult) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DocumentResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentResult) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

func (x *DocumentResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Запрос на получение документа
type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{9}
}

func (x *GetDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ с документом
type GetDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *DocumentResult        `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentResponse) Reset() {
	*x = GetDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentResponse) ProtoMessage() {}

func (x *GetDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentResponse.ProtoReflect.Descriptor instead.
func (*GetDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{10}
}

func (x *GetDocumentResponse) GetDocument() *DocumentResult {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *GetDocumentResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

// Запрос на удаление документа
type DeleteDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentRequest) Reset() {
	*x = DeleteDocumentRequest{}
	mi := &file_api_rag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentRequest) ProtoMessage() {}

func (x *DeleteDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentRequest.ProtoReflect.Descriptor instead.
func (*DeleteDocumentRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Ответ на удаление документа
type DeleteDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocumentResponse) Reset() {
	*x = DeleteDocumentResponse{}
	mi := &file_api_rag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocumentResponse) ProtoMessage() {}

func (x *DeleteDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocumentResponse.ProtoReflect.Descriptor instead.
func (*DeleteDocumentResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDocumentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDocumentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Запрос статистики индекса
type GetIndexStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexStatsRequest) Reset() {
	*x = GetIndexStatsRequest{}
	mi := &file_api_rag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexStatsRequest) ProtoMessage() {}

func (x *GetIndexStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexStatsRequest.ProtoReflect.Descriptor instead.
func (*GetIndexStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{13}
}

// Ответ со статистикой индекса
type GetIndexStatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalDocuments int32                  `protobuf:"varint,1,opt,name=total_documents,json=totalDocuments,proto3" json:"total_documents,omitempty"`
	IndexSizeBytes int64                  `protobuf:"varint,2,opt,name=index_size_bytes,json=indexSizeBytes,proto3" json:"index_size_bytes,omitempty"`
	LastUpdated    string                 `protobuf:"bytes,3,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetIndexStatsResponse) Reset() {
	*x = GetIndexStatsResponse{}
	mi := &file_api_rag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexStatsResponse) ProtoMessage() {}

func (x *GetIndexStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_rag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexStatsResponse.ProtoReflect.Descriptor instead.
func (*GetIndexStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_rag_proto_rawDescGZIP(), []int{14}
}

func (x *GetIndexStatsResponse) GetTotalDocuments() int32 {
	if x != nil {
		return x.TotalDocuments
	}
	return 0
}

func (x *GetIndexStatsResponse) GetIndexSizeBytes() int64 {
	if x != nil {
		return x.IndexSizeBytes
	}
	return 0
}

func (x *GetIndexStatsResponse) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

var File_api_rag_proto protoreflect.FileDescriptor

const file_api_rag_proto_rawDesc = "" +
	"\n" +
	"\rapi/rag.proto\x12\x03rag\"\xef\x02\n" +
	"\x12AddDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1c\n" +
	"\tembedding\x18\x04 \x03(\x02R\tembedding\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.rag.AddDocumentRequest.MetadataEntryR\bmetadata\x128\n" +
	"\vsource_type\x18\x06 \x01(\x0e2\x17.rag.DocumentSourceTypeR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_url\x18\a \x01(\tR\tsourceUrl\x12\"\n" +
	"\rurl_max_depth\x18\b \x01(\x05R\vurlMaxDepth\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"I\n" +
	"\x13AddDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd2\x01\n" +
	"\x16PreviewDocumentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x128\n" +
	"\vsource_type\x18\x02 \x01(\x0e2\x17.rag.DocumentSourceTypeR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_url\x18\x03 \x01(\tR\tsourceUrl\x12%\n" +
	"\x0econtent_base64\x18\x04 \x01(\tR\rcontentBase64\x12\"\n" +
	"\rurl_max_depth\x18\x05 \x01(\x05R\vurlMaxDepth\"i\n" +
	"\x17PreviewDocumentResponse\x12%\n" +
	"\x0eextracted_text\x18\x01 \x01(\tR\rextractedText\x12'\n" +
	"\x0fpages_extracted\x18\x02 \x01(\x05R\x0epagesExtracted\"\xca\x01\n" +
	"\x15CommitDocumentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12D\n" +
	"\bmetadata\x18\x03 \x03(\v2(.rag.CommitDocumentRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x16CommitDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"n\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x121\n" +
	"\x14similarity_threshold\x18\x03 \x01(\x02R\x13similarityThreshold\"`\n" +
	"\x0eSearchResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.rag.DocumentResultR\aresults\x12\x1f\n" +
	"\vtotal_found\x18\x02 \x01(\x05R\n" +
	"totalFound\"\xf7\x01\n" +
	"\x0eDocumentResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12)\n" +
	"\x10similarity_score\x18\x04 \x01(\x02R\x0fsimilarityScore\x12=\n" +
	"\bmetadata\x18\x05 \x03(\v2!.rag.DocumentResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"$\n" +
	"\x12GetDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\\\n" +
	"\x13GetDocumentResponse\x12/\n" +
	"\bdocument\x18\x01 \x01(\v2\x13.rag.DocumentResultR\bdocument\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"'\n" +
	"\x15DeleteDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16DeleteDocumentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x16\n" +
	"\x14GetIndexStatsRequest\"\x8d\x01\n" +
	"\x15GetIndexStatsResponse\x12'\n" +
	"\x0ftotal_documents\x18\x01 \x01(\x05R\x0etotalDocuments\x12(\n" +
	"\x10index_size_bytes\x18\x02 \x01(\x03R\x0eindexSizeBytes\x12!\n" +
	"\flast_updated\x18\x03 \x01(\tR\vlastUpdated*q\n" +
	"\x12DocumentSourceType\x12\x1b\n" +
	"\x17SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SOURCE_TYPE_TEXT\x10\x01\x12\x13\n" +
	"\x0fSOURCE_TYPE_URL\x10\x02\x12\x13\n" +
	"\x0fSOURCE_TYPE_PDF\x10\x032\xb6\x03\n" +
	"\n" +
	"RagService\x12L\n" +
	"\x0fPreviewDocument\x12\x1b.rag.PreviewDocumentRequest\x1a\x1c.rag.PreviewDocumentResponse\x12I\n" +
	"\x0eCommitDocument\x12\x1a.rag.CommitDocumentRequest\x1a\x1b.rag.CommitDocumentResponse\x12:\n" +
	"\x0fSearchDocuments\x12\x12.rag.SearchRequest\x1a\x13.rag.SearchResponse\x12@\n" +
	"\vGetDocument\x12\x17.rag.GetDocumentRequest\x1a\x18.rag.GetDocumentResponse\x12I\n" +
	"\x0eDeleteDocument\x12\x1a.rag.DeleteDocumentRequest\x1a\x1b.rag.DeleteDocumentResponse\x12F\n" +
	"\rGetIndexStats\x12\x19.rag.GetIndexStatsRequest\x1a\x1a.rag.GetIndexStatsResponseB\aZ\x05./ragb\x06proto3"

var (
	file_api_rag_proto_rawDescOnce sync.Once
	file_api_rag_proto_rawDescData []byte
)

func file_api_rag_proto_rawDescGZIP() []byte {
	file_api_rag_proto_rawDescOnce.Do(func() {
		file_api_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_rag_proto_rawDesc), len(file_api_rag_proto_rawDesc)))
	})
	return file_api_rag_proto_rawDescData
}

var file_api_rag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_rag_proto_goTypes = []any{
	(DocumentSourceType)(0),         // 0: rag.DocumentSourceType
	(*AddDocumentRequest)(nil),      // 1: rag.AddDocumentRequest
	(*AddDocumentResponse)(nil),     // 2: rag.AddDocumentResponse
	(*PreviewDocumentRequest)(nil),  // 3: rag.PreviewDocumentRequest
	(*PreviewDocumentResponse)(nil), // 4: rag.PreviewDocumentResponse
	(*CommitDocumentRequest)(nil),   // 5: rag.CommitDocumentRequest
	(*CommitDocumentResponse)(nil),  // 6: rag.CommitDocumentResponse
	(*SearchRequest)(nil),           // 7: rag.SearchRequest
	(*SearchResponse)(nil),          // 8: rag.SearchResponse
	(*DocumentResult)(nil),          // 9: rag.DocumentResult
	(*GetDocumentRequest)(nil),      // 10: rag.GetDocumentRequest
	(*GetDocumentResponse)(nil),     // 11: rag.GetDocumentResponse
	(*DeleteDocumentRequest)(nil),   // 12: rag.DeleteDocumentRequest
	(*DeleteDocumentResponse)(nil),  // 13: rag.DeleteDocumentResponse
	(*GetIndexStatsRequest)(nil),    // 14: rag.GetIndexStatsRequest
	(*GetIndexStatsResponse)(nil),   // 15: rag.GetIndexStatsResponse
	nil,                             // 16: rag.AddDocumentRequest.MetadataEntry
	nil,                             // 17: rag.CommitDocumentRequest.MetadataEntry
	nil,                             // 18: rag.DocumentResult.MetadataEntry
}
var file_api_rag_proto_depIdxs = []int32{
	16, // 0: rag.AddDocumentRequest.metadata:type_name -> rag.AddDocumentRequest.MetadataEntry
	0,  // 1: rag.AddDocumentRequest.source_type:type_name -> rag.DocumentSourceType
	0,  // 2: rag.PreviewDocumentRequest.source_type:type_name -> rag.DocumentSourceType
	17, // 3: rag.CommitDocumentRequest.metadata:type_name -> rag.CommitDocumentRequest.MetadataEntry
	9,  // 4: rag.SearchResponse.results:type_name -> rag.DocumentResult
	18, // 5: rag.DocumentResult.metadata:type_name -> rag.DocumentResult.MetadataEntry
	9,  // 6: rag.GetDocumentResponse.document:type_name -> rag.DocumentResult
	3,  // 7: rag.RagService.PreviewDocument:input_type -> rag.PreviewDocumentRequest
	5,  // 8: rag.RagService.CommitDocument:input_type -> rag.CommitDocumentRequest
	7,  // 9: rag.RagService.SearchDocuments:input_type -> rag.SearchRequest
	10, // 10: rag.RagService.GetDocument:input_type -> rag.GetDocumentRequest
	12, // 11: rag.RagService.DeleteDocument:input_type -> rag.DeleteDocumentRequest
	14, // 12: rag.RagService.GetIndexStats:input_type -> rag.GetIndexStatsRequest
	4,  // 13: rag.RagService.PreviewDocument:output_type -> rag.PreviewDocumentResponse
	6,  // 14: rag.RagService.CommitDocument:output_type -> rag.CommitDocumentResponse
	8,  // 15: rag.RagService.SearchDocuments:output_type -> rag.SearchResponse
	11, // 16: rag.RagService.GetDocument:output_type -> rag.GetDocumentResponse
	13, // 17: rag.RagService.DeleteDocument:output_type -> rag.DeleteDocumentResponse
	15, // 18: rag.RagService.GetIndexStats:output_type -> rag.GetIndexStatsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_rag_proto_init() }
func file_api_rag_proto_init() {
	if File_api_rag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_rag_proto_rawDesc), len(file_api_rag_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rag_proto_goTypes,
		DependencyIndexes: file_api_rag_proto_depIdxs,
		EnumInfos:         file_api_rag_proto_enumTypes,
		MessageInfos:      file_api_rag_proto_msgTypes,
	}.Build()
	File_api_rag_proto = out.File
	file_api_rag_proto_goTypes = nil
	file_api_rag_proto_depIdxs = nil
}
