# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rag_pb2 as rag__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RagServiceStub(object):
    """RAG сервис для работы с документами и поиском
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PreviewDocument = channel.unary_unary(
                '/rag.RagService/PreviewDocument',
                request_serializer=rag__pb2.PreviewDocumentRequest.SerializeToString,
                response_deserializer=rag__pb2.PreviewDocumentResponse.FromString,
                _registered_method=True)
        self.CommitDocument = channel.unary_unary(
                '/rag.RagService/CommitDocument',
                request_serializer=rag__pb2.CommitDocumentRequest.SerializeToString,
                response_deserializer=rag__pb2.CommitDocumentResponse.FromString,
                _registered_method=True)
        self.SearchDocuments = channel.unary_unary(
                '/rag.RagService/SearchDocuments',
                request_serializer=rag__pb2.SearchRequest.SerializeToString,
                response_deserializer=rag__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetDocument = channel.unary_unary(
                '/rag.RagService/GetDocument',
                request_serializer=rag__pb2.GetDocumentRequest.SerializeToString,
                response_deserializer=rag__pb2.GetDocumentResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/rag.RagService/DeleteDocument',
                request_serializer=rag__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=rag__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)
        self.GetIndexStats = channel.unary_unary(
                '/rag.RagService/GetIndexStats',
                request_serializer=rag__pb2.GetIndexStatsRequest.SerializeToString,
                response_deserializer=rag__pb2.GetIndexStatsResponse.FromString,
                _registered_method=True)
        self.GetRagSettings = channel.unary_unary(
                '/rag.RagService/GetRagSettings',
                request_serializer=rag__pb2.GetRagSettingsRequest.SerializeToString,
                response_deserializer=rag__pb2.GetRagSettingsResponse.FromString,
                _registered_method=True)
        self.UpdateRagSettings = channel.unary_unary(
                '/rag.RagService/UpdateRagSettings',
                request_serializer=rag__pb2.UpdateRagSettingsRequest.SerializeToString,
                response_deserializer=rag__pb2.UpdateRagSettingsResponse.FromString,
                _registered_method=True)
        self.GetRagSettingsHistory = channel.unary_unary(
                '/rag.RagService/GetRagSettingsHistory',
                request_serializer=rag__pb2.GetRagSettingsHistoryRequest.SerializeToString,
                response_deserializer=rag__pb2.GetRagSettingsHistoryResponse.FromString,
                _registered_method=True)
        self.GetDocumentHistory = channel.unary_unary(
                '/rag.RagService/GetDocumentHistory',
                request_serializer=rag__pb2.GetDocumentHistoryRequest.SerializeToString,
                response_deserializer=rag__pb2.GetDocumentHistoryResponse.FromString,
                _registered_method=True)
        self.RollbackDocument = channel.unary_unary(
                '/rag.RagService/RollbackDocument',
                request_serializer=rag__pb2.RollbackDocumentRequest.SerializeToString,
                response_deserializer=rag__pb2.RollbackDocumentResponse.FromString,
                _registered_method=True)
        self.UpdateDocument = channel.unary_unary(
                '/rag.RagService/UpdateDocument',
                request_serializer=rag__pb2.UpdateDocumentRequest.SerializeToString,
                response_deserializer=rag__pb2.UpdateDocumentResponse.FromString,
                _registered_method=True)
        self.GetAllDocuments = channel.unary_unary(
                '/rag.RagService/GetAllDocuments',
                request_serializer=rag__pb2.GetAllDocumentsRequest.SerializeToString,
                response_deserializer=rag__pb2.GetAllDocumentsResponse.FromString,
                _registered_method=True)
        self.GetQueryLogs = channel.unary_unary(
                '/rag.RagService/GetQueryLogs',
                request_serializer=rag__pb2.GetQueryLogsRequest.SerializeToString,
                response_deserializer=rag__pb2.GetQueryLogsResponse.FromString,
                _registered_method=True)
        self.DiscoverLinks = channel.unary_unary(
                '/rag.RagService/DiscoverLinks',
                request_serializer=rag__pb2.DiscoverLinksRequest.SerializeToString,
                response_deserializer=rag__pb2.DiscoverLinksResponse.FromString,
                _registered_method=True)
        self.ScrapeUrls = channel.unary_unary(
                '/rag.RagService/ScrapeUrls',
                request_serializer=rag__pb2.ScrapeUrlsRequest.SerializeToString,
                response_deserializer=rag__pb2.ScrapeUrlsResponse.FromString,
                _registered_method=True)
        self.GetDocumentIdsByQuery = channel.unary_unary(
                '/rag.RagService/GetDocumentIdsByQuery',
                request_serializer=rag__pb2.GetDocumentIdsRequest.SerializeToString,
                response_deserializer=rag__pb2.GetDocumentIdsResponse.FromString,
                _registered_method=True)
        self.AdminLogin = channel.unary_unary(
                '/rag.RagService/AdminLogin',
                request_serializer=rag__pb2.AdminLoginRequest.SerializeToString,
                response_deserializer=rag__pb2.AdminLoginResponse.FromString,
                _registered_method=True)
        self.AdminLogout = channel.unary_unary(
                '/rag.RagService/AdminLogout',
                request_serializer=rag__pb2.AdminLogoutRequest.SerializeToString,
                response_deserializer=rag__pb2.AdminLogoutResponse.FromString,
                _registered_method=True)
        self.AddAdmin = channel.unary_unary(
                '/rag.RagService/AddAdmin',
                request_serializer=rag__pb2.AddAdminRequest.SerializeToString,
                response_deserializer=rag__pb2.AddAdminResponse.FromString,
                _registered_method=True)
        self.RemoveAdmin = channel.unary_unary(
                '/rag.RagService/RemoveAdmin',
                request_serializer=rag__pb2.RemoveAdminRequest.SerializeToString,
                response_deserializer=rag__pb2.RemoveAdminResponse.FromString,
                _registered_method=True)
        self.ListAdmins = channel.unary_unary(
                '/rag.RagService/ListAdmins',
                request_serializer=rag__pb2.ListAdminsRequest.SerializeToString,
                response_deserializer=rag__pb2.ListAdminsResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/rag.RagService/ValidateToken',
                request_serializer=rag__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=rag__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)


class RagServiceServicer(object):
    """RAG сервис для работы с документами и поиском
    """

    def PreviewDocument(self, request, context):
        """Предпросмотр: извлечь текст из PDF/URL без сохранения
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitDocument(self, request, context):
        """Сохранить документ с готовым текстом
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchDocuments(self, request, context):
        """Поиск документов по запросу
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocument(self, request, context):
        """Получить документ по ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Удалить документ по ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexStats(self, request, context):
        """Получить статистику индекса
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRagSettings(self, request, context):
        """Получить все настройки RAG
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRagSettings(self, request, context):
        """Обновить настройку RAG
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRagSettingsHistory(self, request, context):
        """Получить историю изменений настроек
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentHistory(self, request, context):
        """Получить историю версий документа
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackDocument(self, request, context):
        """Откатить документ к определённой версии
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateDocument(self, request, context):
        """Обновить документ (название и/или содержимое)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllDocuments(self, request, context):
        """Получить список всех документов
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueryLogs(self, request, context):
        """Получить логи запросов с пагинацией
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverLinks(self, request, context):
        """Найти ссылки на странице (BFS)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ScrapeUrls(self, request, context):
        """Скрапить выбранные URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentIdsByQuery(self, request, context):
        """Получить только ID документов по запросу (для метрик)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminLogin(self, request, context):
        """============= ADMIN Methods (require JWT token) =============

        Админ логин (без JWT)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdminLogout(self, request, context):
        """Админ логаут (требует JWT)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddAdmin(self, request, context):
        """Добавить админа (требует JWT)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveAdmin(self, request, context):
        """Удалить админа (требует JWT)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAdmins(self, request, context):
        """Список всех админов (требует JWT)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Валидировать токен (для проверки на фронте)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PreviewDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewDocument,
                    request_deserializer=rag__pb2.PreviewDocumentRequest.FromString,
                    response_serializer=rag__pb2.PreviewDocumentResponse.SerializeToString,
            ),
            'CommitDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitDocument,
                    request_deserializer=rag__pb2.CommitDocumentRequest.FromString,
                    response_serializer=rag__pb2.CommitDocumentResponse.SerializeToString,
            ),
            'SearchDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchDocuments,
                    request_deserializer=rag__pb2.SearchRequest.FromString,
                    response_serializer=rag__pb2.SearchResponse.SerializeToString,
            ),
            'GetDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocument,
                    request_deserializer=rag__pb2.GetDocumentRequest.FromString,
                    response_serializer=rag__pb2.GetDocumentResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=rag__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=rag__pb2.DeleteDocumentResponse.SerializeToString,
            ),
            'GetIndexStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexStats,
                    request_deserializer=rag__pb2.GetIndexStatsRequest.FromString,
                    response_serializer=rag__pb2.GetIndexStatsResponse.SerializeToString,
            ),
            'GetRagSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRagSettings,
                    request_deserializer=rag__pb2.GetRagSettingsRequest.FromString,
                    response_serializer=rag__pb2.GetRagSettingsResponse.SerializeToString,
            ),
            'UpdateRagSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRagSettings,
                    request_deserializer=rag__pb2.UpdateRagSettingsRequest.FromString,
                    response_serializer=rag__pb2.UpdateRagSettingsResponse.SerializeToString,
            ),
            'GetRagSettingsHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRagSettingsHistory,
                    request_deserializer=rag__pb2.GetRagSettingsHistoryRequest.FromString,
                    response_serializer=rag__pb2.GetRagSettingsHistoryResponse.SerializeToString,
            ),
            'GetDocumentHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentHistory,
                    request_deserializer=rag__pb2.GetDocumentHistoryRequest.FromString,
                    response_serializer=rag__pb2.GetDocumentHistoryResponse.SerializeToString,
            ),
            'RollbackDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackDocument,
                    request_deserializer=rag__pb2.RollbackDocumentRequest.FromString,
                    response_serializer=rag__pb2.RollbackDocumentResponse.SerializeToString,
            ),
            'UpdateDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateDocument,
                    request_deserializer=rag__pb2.UpdateDocumentRequest.FromString,
                    response_serializer=rag__pb2.UpdateDocumentResponse.SerializeToString,
            ),
            'GetAllDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllDocuments,
                    request_deserializer=rag__pb2.GetAllDocumentsRequest.FromString,
                    response_serializer=rag__pb2.GetAllDocumentsResponse.SerializeToString,
            ),
            'GetQueryLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueryLogs,
                    request_deserializer=rag__pb2.GetQueryLogsRequest.FromString,
                    response_serializer=rag__pb2.GetQueryLogsResponse.SerializeToString,
            ),
            'DiscoverLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverLinks,
                    request_deserializer=rag__pb2.DiscoverLinksRequest.FromString,
                    response_serializer=rag__pb2.DiscoverLinksResponse.SerializeToString,
            ),
            'ScrapeUrls': grpc.unary_unary_rpc_method_handler(
                    servicer.ScrapeUrls,
                    request_deserializer=rag__pb2.ScrapeUrlsRequest.FromString,
                    response_serializer=rag__pb2.ScrapeUrlsResponse.SerializeToString,
            ),
            'GetDocumentIdsByQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentIdsByQuery,
                    request_deserializer=rag__pb2.GetDocumentIdsRequest.FromString,
                    response_serializer=rag__pb2.GetDocumentIdsResponse.SerializeToString,
            ),
            'AdminLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminLogin,
                    request_deserializer=rag__pb2.AdminLoginRequest.FromString,
                    response_serializer=rag__pb2.AdminLoginResponse.SerializeToString,
            ),
            'AdminLogout': grpc.unary_unary_rpc_method_handler(
                    servicer.AdminLogout,
                    request_deserializer=rag__pb2.AdminLogoutRequest.FromString,
                    response_serializer=rag__pb2.AdminLogoutResponse.SerializeToString,
            ),
            'AddAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.AddAdmin,
                    request_deserializer=rag__pb2.AddAdminRequest.FromString,
                    response_serializer=rag__pb2.AddAdminResponse.SerializeToString,
            ),
            'RemoveAdmin': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveAdmin,
                    request_deserializer=rag__pb2.RemoveAdminRequest.FromString,
                    response_serializer=rag__pb2.RemoveAdminResponse.SerializeToString,
            ),
            'ListAdmins': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAdmins,
                    request_deserializer=rag__pb2.ListAdminsRequest.FromString,
                    response_serializer=rag__pb2.ListAdminsResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=rag__pb2.ValidateTokenRequest.FromString,
                    response_serializer=rag__pb2.ValidateTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService(object):
    """RAG сервис для работы с документами и поиском
    """

    @staticmethod
    def PreviewDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/PreviewDocument',
            rag__pb2.PreviewDocumentRequest.SerializeToString,
            rag__pb2.PreviewDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/CommitDocument',
            rag__pb2.CommitDocumentRequest.SerializeToString,
            rag__pb2.CommitDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/SearchDocuments',
            rag__pb2.SearchRequest.SerializeToString,
            rag__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetDocument',
            rag__pb2.GetDocumentRequest.SerializeToString,
            rag__pb2.GetDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/DeleteDocument',
            rag__pb2.DeleteDocumentRequest.SerializeToString,
            rag__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndexStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetIndexStats',
            rag__pb2.GetIndexStatsRequest.SerializeToString,
            rag__pb2.GetIndexStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRagSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetRagSettings',
            rag__pb2.GetRagSettingsRequest.SerializeToString,
            rag__pb2.GetRagSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRagSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/UpdateRagSettings',
            rag__pb2.UpdateRagSettingsRequest.SerializeToString,
            rag__pb2.UpdateRagSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRagSettingsHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetRagSettingsHistory',
            rag__pb2.GetRagSettingsHistoryRequest.SerializeToString,
            rag__pb2.GetRagSettingsHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetDocumentHistory',
            rag__pb2.GetDocumentHistoryRequest.SerializeToString,
            rag__pb2.GetDocumentHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/RollbackDocument',
            rag__pb2.RollbackDocumentRequest.SerializeToString,
            rag__pb2.RollbackDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/UpdateDocument',
            rag__pb2.UpdateDocumentRequest.SerializeToString,
            rag__pb2.UpdateDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetAllDocuments',
            rag__pb2.GetAllDocumentsRequest.SerializeToString,
            rag__pb2.GetAllDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueryLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetQueryLogs',
            rag__pb2.GetQueryLogsRequest.SerializeToString,
            rag__pb2.GetQueryLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/DiscoverLinks',
            rag__pb2.DiscoverLinksRequest.SerializeToString,
            rag__pb2.DiscoverLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ScrapeUrls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/ScrapeUrls',
            rag__pb2.ScrapeUrlsRequest.SerializeToString,
            rag__pb2.ScrapeUrlsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentIdsByQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/GetDocumentIdsByQuery',
            rag__pb2.GetDocumentIdsRequest.SerializeToString,
            rag__pb2.GetDocumentIdsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/AdminLogin',
            rag__pb2.AdminLoginRequest.SerializeToString,
            rag__pb2.AdminLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdminLogout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/AdminLogout',
            rag__pb2.AdminLogoutRequest.SerializeToString,
            rag__pb2.AdminLogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/AddAdmin',
            rag__pb2.AddAdminRequest.SerializeToString,
            rag__pb2.AddAdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveAdmin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/RemoveAdmin',
            rag__pb2.RemoveAdminRequest.SerializeToString,
            rag__pb2.RemoveAdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAdmins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/ListAdmins',
            rag__pb2.ListAdminsRequest.SerializeToString,
            rag__pb2.ListAdminsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.RagService/ValidateToken',
            rag__pb2.ValidateTokenRequest.SerializeToString,
            rag__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
