package stubs

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"graphql-gateway/internal/app/generated"
)

// PreviewDocument is the resolver for the previewDocument field.
func (r *mutationResolver) PreviewDocument(ctx context.Context, input generated.PreviewDocumentInput) (*generated.PreviewDocumentResult, error) {
	panic(fmt.Errorf("not implemented: PreviewDocument - previewDocument"))
}

// CommitDocument is the resolver for the commitDocument field.
func (r *mutationResolver) CommitDocument(ctx context.Context, input generated.CommitDocumentInput) (*generated.CommitDocumentResult, error) {
	panic(fmt.Errorf("not implemented: CommitDocument - commitDocument"))
}

// DeleteDocument is the resolver for the deleteDocument field.
func (r *mutationResolver) DeleteDocument(ctx context.Context, id string) (*generated.DeleteDocumentResult, error) {
	panic(fmt.Errorf("not implemented: DeleteDocument - deleteDocument"))
}

// UpdateRagSetting is the resolver for the updateRagSetting field.
func (r *mutationResolver) UpdateRagSetting(ctx context.Context, key string, value string, changedBy *string) (*generated.UpdateSettingsResult, error) {
	panic(fmt.Errorf("not implemented: UpdateRagSetting - updateRagSetting"))
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
