package stubs

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"graphql-gateway/internal/app/generated"
)

// Ask is the resolver for the ask field.
func (r *queryResolver) Ask(ctx context.Context, question string) (string, error) {
	panic(fmt.Errorf("not implemented: Ask - ask"))
}

// SearchDocuments is the resolver for the searchDocuments field.
func (r *queryResolver) SearchDocuments(ctx context.Context, query string, limit *int, threshold *float64) ([]*generated.DocumentResult, error) {
	panic(fmt.Errorf("not implemented: SearchDocuments - searchDocuments"))
}

// GetDocument is the resolver for the getDocument field.
func (r *queryResolver) GetDocument(ctx context.Context, id string) (*generated.Document, error) {
	panic(fmt.Errorf("not implemented: GetDocument - getDocument"))
}

// GetIndexStats is the resolver for the getIndexStats field.
func (r *queryResolver) GetIndexStats(ctx context.Context) (*generated.IndexStats, error) {
	panic(fmt.Errorf("not implemented: GetIndexStats - getIndexStats"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
