package stubs

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"graphql-gateway/internal/app/generated"
)

// Ask is the resolver for the ask field.
func (r *queryResolver) Ask(ctx context.Context, question string) (string, error) {
	panic(fmt.Errorf("not implemented: Ask - ask"))
}

// SearchDocuments is the resolver for the searchDocuments field.
func (r *queryResolver) SearchDocuments(ctx context.Context, query string, limit *int, threshold *float64) ([]*generated.DocumentResult, error) {
	panic(fmt.Errorf("not implemented: SearchDocuments - searchDocuments"))
}

// GetDocument is the resolver for the getDocument field.
func (r *queryResolver) GetDocument(ctx context.Context, id string) (*generated.Document, error) {
	panic(fmt.Errorf("not implemented: GetDocument - getDocument"))
}

// GetIndexStats is the resolver for the getIndexStats field.
func (r *queryResolver) GetIndexStats(ctx context.Context) (*generated.IndexStats, error) {
	panic(fmt.Errorf("not implemented: GetIndexStats - getIndexStats"))
}

// GetRagSettings is the resolver for the getRagSettings field.
func (r *queryResolver) GetRagSettings(ctx context.Context) ([]*generated.SettingEntry, error) {
	panic(fmt.Errorf("not implemented: GetRagSettings - getRagSettings"))
}

// GetRagSettingsHistory is the resolver for the getRagSettingsHistory field.
func (r *queryResolver) GetRagSettingsHistory(ctx context.Context, limit *int) ([]*generated.SettingsHistoryEntry, error) {
	panic(fmt.Errorf("not implemented: GetRagSettingsHistory - getRagSettingsHistory"))
}

// GetDocumentHistory is the resolver for the getDocumentHistory field.
func (r *queryResolver) GetDocumentHistory(ctx context.Context, documentID string, limit *int) ([]*generated.DocumentVersion, error) {
	panic(fmt.Errorf("not implemented: GetDocumentHistory - getDocumentHistory"))
}

// GetDocuments is the resolver for the getDocuments field.
func (r *queryResolver) GetDocuments(ctx context.Context) ([]*generated.DocumentListItem, error) {
	panic(fmt.Errorf("not implemented: GetDocuments - getDocuments"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
